import type * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";

export const hexagonLanguage = "hexagon";

export const hexagonTokens: monaco.languages.IMonarchLanguage = {
  // Monarch rebuilds rule regexes using language-level flags, so the Unicode
  // flag must live here for the identifier property escapes to remain valid.
  unicode: true,
  keywords: [
    "and",
    "catch",
    "constraint",
    "derive",
    "else",
    "exception",
    "export",
    "extern",
    "false",
    "finally",
    "for",
    "fun",
    "honor",
    "iff",
    "if",
    "implies",
    "import",
    "in",
    "let",
    "match",
    "not",
    "or",
    "record",
    "then",
    "true",
    "try",
    "type",
    "union",
    "var",
    "while",
  ],
  operators: [
    "+",
    "-",
    "*",
    "/",
    "++",
    "==",
    "!=",
    "<",
    ">",
    "<=",
    ">=",
    "|>",
  ],
  tokenizer: {
    root: [
      [/\/\/.*$/u, "comment"],
      [/^module(?=[ \t]+[\p{Uppercase}\p{Lt}][$\u200C\u200D_\p{ID_Continue}]*[ \t]*$)/u, "keyword"],
      [/^end[ \t]+module(?=[ \t]+[\p{Uppercase}\p{Lt}][$\u200C\u200D_\p{ID_Continue}]*[ \t]*$)/u, "keyword"],
      [/__hex_[$\u200C\u200D_\p{ID_Continue}]*/u, "invalid"],
      [/_(?![$\u200C\u200D_\p{ID_Continue}])/u, "delimiter"],
      [/[\p{Uppercase}\p{Lt}][$\u200C\u200D_\p{ID_Continue}]*/u, "type.identifier"],
      [/(?![\p{Uppercase}\p{Lt}])[$_\p{ID_Start}][$\u200C\u200D_\p{ID_Continue}]*/u, {
        cases: { "@keywords": "keyword", "@default": "identifier" },
      }],
      [/\d+(?:\.\d+)?n?/u, "number"],
      [/"(?:[^"\\]|\\.)*"/u, "string"],
      [/[()\[\]{},.:]/u, "delimiter"],
      [/[+*/<>=!|-]+/u, "operator"],
    ],
  },
};
