/**
 * Embedded copies of the canonical `stdlib/` prelude sources. Do not edit by hand.
 * Regenerate with `npm run generate:prelude`; a conformance test asserts these
 * never drift from the originals.
 */

export const PRELUDE_SOURCES: Readonly<Record<string, string>> = {
  "Prelude.hex":
    "// Prelude nominals that are implicitly in scope in every Hexagon module.\n"
    + "//\n"
    + "// This file is the canonical, human-facing source of the prelude. The compiler\n"
    + "// embeds an identical copy in `compiler/src/prelude.ts` so that `compileProject`\n"
    + "// stays filesystem-free; a test asserts the two never drift.\n"
    + "export union Ordering derives (Eq, Show) =\n"
    + "    | Less\n"
    + "    | Equal\n"
    + "    | Greater\n",
  "Option.hex":
    "// The canonical optional-value union used by total standard-library accessors.\n"
    + "export union Option(a) derives (Eq, Show) =\n"
    + "    | Some(value: a)\n"
    + "    | None\n",
  "Seq.hex":
    "// The lazy sequence type (Loops §6, `spec/notes/seq-core-representation.md`).\n"
    + "//\n"
    + "// `Option`, `Some`, and `None` are implicitly in scope via the prelude\n"
    + "// (Modules §5.5). This module declares `Seq(a)`; nothing in the compiler does.\n"
    + "//\n"
    + "// A `Seq` is a record carrying its own deferred pull thunk (OCaml's\n"
    + "// `unit -> node`). The thunk is what defers: constructing a combinator runs\n"
    + "// nothing, so an infinite `Seq` is a finite value and driving one step is O(1).\n"
    + "//\n"
    + "// Why a record-of-closure and not a union of cases: a defunctionalized\n"
    + "// `union Seq(a) = Mapped(source: Seq(b), f: b -> a) | ...` cannot be written,\n"
    + "// because `b` would be an existential in the union and Hexagon's HM does not\n"
    + "// express that. Hiding the source and transform *inside a closure* keeps that\n"
    + "// type from escaping into `Seq(a)`. This is the load-bearing decision.\n"
    + "//\n"
    + "// Persistence here is by **re-derivation**, not memoization: re-driving a `Seq`\n"
    + "// recomputes it, and therefore *replays any effects* its steps perform (Loops\n"
    + "// §6.4, where re-derivation is the default and `memoize` the opt-in). Neither\n"
    + "// the memoizing spine, the opt-in `memoize`, nor the two foreign shims\n"
    + "// (`fromJsIterator`, `toJsIterable`) can live in this file: all of them need a\n"
    + "// mutable buffer, and Statements §6.2 forbids mutable capture in closures. They\n"
    + "// are compiler/runtime-provided at the FFI Part 3 boundary.\n"
    + "//\n"
    + "// `opaque`: the pull field is representation, not surface. Consumers use the\n"
    + "// §6.2 protocol (`next`) and the combinators below.\n"
    + "export opaque record Seq(a) = { pull: () -> Option((a, Seq(a))) }\n"
    + "\n"
    + "// The Loops §6.2 protocol, thin over the field. Not recursive, so `let` (N6).\n"
    + "// The field is named `pull`, not `next`, so the field access never shadows the\n"
    + "// protocol; the call is written `(source.pull)()` because a bare\n"
    + "// `source.pull(...)` on a nominal head is a companion dispatch, not a field read\n"
    + "// (Products §3.2).\n"
    + "export let next(source: Seq(a)): Option((a, Seq(a))) = (source.pull)()\n"
    + "\n"
    + "// ---------------------------------------------------------------------------\n"
    + "// 1. One-step `pull`: one input element yields one output element.\n"
    + "// ---------------------------------------------------------------------------\n"
    + "\n"
    + "export let empty: Seq(a) = Seq({ pull = () => None })\n"
    + "\n"
    + "export let singleton(value: a): Seq(a) = Seq({ pull = () => Some((value, empty)) })\n"
    + "\n"
    + "export let cons(value: a, rest: Seq(a)): Seq(a) = Seq({ pull = () => Some((value, rest)) })\n"
    + "\n"
    + "export fun iterate(seed: a, step: a -> a): Seq(a) =\n"
    + "    Seq({ pull = () => Some((seed, iterate(step(seed), step))) })\n"
    + "\n"
    + "// Each combinator binds its pull step as a local lambda and then wraps it. The\n"
    + "// step cannot be written inline as the record-field value: a multi-line `match`\n"
    + "// there makes the layout algorithm close the record literal at the first arm.\n"
    + "export fun map(source: Seq(a), transform: a -> b): Seq(b) =\n"
    + "    let step = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) => Some((transform(value), map(rest, transform)))\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export fun take(source: Seq(a), count: Int): Seq(a) =\n"
    + "    if count <= 0 then\n"
    + "        empty\n"
    + "    else\n"
    + "        let step = () =>\n"
    + "            match next(source)\n"
    + "                None => None\n"
    + "                Some((value, rest)) => Some((value, take(rest, count - 1)))\n"
    + "        Seq({ pull = step })\n"
    + "\n"
    + "export fun takeWhile(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) =>\n"
    + "                if keep(value) then\n"
    + "                    Some((value, takeWhile(rest, keep)))\n"
    + "                else\n"
    + "                    None\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export fun unfold(seed: b, produce: b -> Option((a, b))): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        match produce(seed)\n"
    + "            None => None\n"
    + "            Some((value, nextSeed)) => Some((value, unfold(nextSeed, produce)))\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export fun zipWith(left: Seq(a), right: Seq(b), combine: (a, b) -> c): Seq(c) =\n"
    + "    let step = () =>\n"
    + "        match next(left)\n"
    + "            None => None\n"
    + "            Some((leftValue, leftRest)) =>\n"
    + "                match next(right)\n"
    + "                    None => None\n"
    + "                    Some((rightValue, rightRest)) =>\n"
    + "                        Some((combine(leftValue, rightValue), zipWith(leftRest, rightRest, combine)))\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export let zip(left: Seq(a), right: Seq(b)): Seq((a, b)) =\n"
    + "    zipWith(left, right, (leftValue, rightValue) => (leftValue, rightValue))\n"
    + "\n"
    + "// `concat`'s exhaust-then-switch is one bounded extra pull, not a skip loop:\n"
    + "// when the first sequence is spent it hands straight to the second's thunk.\n"
    + "export fun concat(first: Seq(a), second: Seq(a)): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        match next(first)\n"
    + "            None => next(second)\n"
    + "            Some((value, rest)) => Some((value, concat(rest, second)))\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "// ---------------------------------------------------------------------------\n"
    + "// 2. `pull` needs a constant-stack `while`: many input elements per output.\n"
    + "// ---------------------------------------------------------------------------\n"
    + "//\n"
    + "// When a combinator may consume many source elements to yield one, its step is a\n"
    + "// `while` loop threading a `var` cursor — never self-recursion, because Loops\n"
    + "// §6.5 promises no TCO and a long run of skipped elements would otherwise grow\n"
    + "// the stack. The sentinel `var searching` stands in for the absent `break`\n"
    + "// (Loops §9.4).\n"
    + "\n"
    + "export fun filter(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = true\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := false\n"
    + "                Some((value, rest)) =>\n"
    + "                    if keep(value) then\n"
    + "                        result := Some((value, filter(rest, keep)))\n"
    + "                        searching := false\n"
    + "                    else\n"
    + "                        current := rest\n"
    + "        result\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "// `drop` and `dropWhile` need no self-reference: they skip a run of elements and\n"
    + "// then hand back the underlying pull, so both are `let` (N6).\n"
    + "export let drop(source: Seq(a), count: Int): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        var current = source\n"
    + "        var remaining = count\n"
    + "        var result = None\n"
    + "        var running = true\n"
    + "        while running\n"
    + "            if remaining <= 0 then\n"
    + "                result := next(current)\n"
    + "                running := false\n"
    + "            else\n"
    + "                match next(current)\n"
    + "                    None => running := false\n"
    + "                    Some((_, rest)) =>\n"
    + "                        current := rest\n"
    + "                        remaining := remaining - 1\n"
    + "        result\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export let dropWhile(source: Seq(a), discard: a -> Bool): Seq(a) =\n"
    + "    let step = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = true\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := false\n"
    + "                Some((value, rest)) =>\n"
    + "                    if discard(value) then\n"
    + "                        current := rest\n"
    + "                    else\n"
    + "                        result := Some((value, rest))\n"
    + "                        searching := false\n"
    + "        result\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "// `flatMap` is the hardest of these: draining empty sub-sequences to reach the\n"
    + "// next element is still one `while`, never a stack. `pending` is the partially\n"
    + "// consumed inner sequence carried between pulls, which is why the recursive knot\n"
    + "// is tied through `flatMapWith` rather than through `flatMap` itself.\n"
    + "// Private: `pending` is recursion plumbing, not public surface. `flatMap` below\n"
    + "// is the entire exported face of this pair.\n"
    + "fun flatMapWith(source: Seq(a), transform: a -> Seq(b), pending: Seq(b)): Seq(b) =\n"
    + "    let step = () =>\n"
    + "        var outer = source\n"
    + "        var inner = pending\n"
    + "        var result = None\n"
    + "        var searching = true\n"
    + "        while searching\n"
    + "            match next(inner)\n"
    + "                Some((value, rest)) =>\n"
    + "                    result := Some((value, flatMapWith(outer, transform, rest)))\n"
    + "                    searching := false\n"
    + "                None =>\n"
    + "                    match next(outer)\n"
    + "                        None => searching := false\n"
    + "                        Some((outerValue, outerRest)) =>\n"
    + "                            outer := outerRest\n"
    + "                            inner := transform(outerValue)\n"
    + "        result\n"
    + "    Seq({ pull = step })\n"
    + "\n"
    + "export let flatMap(source: Seq(a), transform: a -> Seq(b)): Seq(b) =\n"
    + "    flatMapWith(source, transform, empty)\n"
    + "\n"
    + "// ---------------------------------------------------------------------------\n"
    + "// 3. Consumers: drive a `Seq` to a value.\n"
    + "// ---------------------------------------------------------------------------\n"
    + "//\n"
    + "// The Loops §6.3 \"external iteration\" idiom. All are `let`: the loop, not\n"
    + "// recursion, does the driving.\n"
    + "\n"
    + "export let fold(source: Seq(a), initial: b, combine: (b, a) -> b): b =\n"
    + "    var accumulator = initial\n"
    + "    var current = source\n"
    + "    var running = true\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := false\n"
    + "            Some((value, rest)) =>\n"
    + "                accumulator := combine(accumulator, value)\n"
    + "                current := rest\n"
    + "    accumulator\n"
    + "\n"
    + "export let length(source: Seq(a)): Int =\n"
    + "    var total = 0\n"
    + "    var current = source\n"
    + "    var running = true\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := false\n"
    + "            Some((_, rest)) =>\n"
    + "                total := total + 1\n"
    + "                current := rest\n"
    + "    total\n"
    + "\n"
    + "export let forEach(source: Seq(a), action: a -> Unit): Unit =\n"
    + "    var current = source\n"
    + "    var running = true\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := false\n"
    + "            Some((value, rest)) =>\n"
    + "                action(value)\n"
    + "                current := rest\n"
    + "\n"
    + "export let find(source: Seq(a), matches: a -> Bool): Option(a) =\n"
    + "    var current = source\n"
    + "    var result = None\n"
    + "    var searching = true\n"
    + "    while searching\n"
    + "        match next(current)\n"
    + "            None => searching := false\n"
    + "            Some((value, rest)) =>\n"
    + "                if matches(value) then\n"
    + "                    result := Some(value)\n"
    + "                    searching := false\n"
    + "                else\n"
    + "                    current := rest\n"
    + "    result\n"
    + "\n"
    + "export let any(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    match find(source, matches)\n"
    + "        None => false\n"
    + "        Some(_) => true\n"
    + "\n"
    + "export let all(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    not any(source, value => not matches(value))\n",
  "Result.hex":
    "// The canonical success-or-error union used across the standard library.\n"
    + "// Success type first, per the subject-first convention (Functions §5.3).\n"
    + "export union Result(a, e) =\n"
    + "    | Ok(value: a)\n"
    + "    | Err(error: e)\n",
};
