/**
 * Embedded copies of the canonical `stdlib/` prelude sources. Do not edit by hand.
 * Regenerate with `npm run generate:prelude`; a conformance test asserts these
 * never drift from the originals.
 */

export const PRELUDE_SOURCES: Readonly<Record<string, string>> = {
  "Bool.hex":
    "// The boolean type. Constructor order `False | True` is normative: it is what makes\n"
    + "// the derived `Ord` order `False < True`.\n"
    + "export union Bool derives (Eq, Ord, Show, Hash) =\n"
    + "    | False\n"
    + "    | True\n",
  "Prelude.hex":
    "// The outcome of comparing two values, as produced by `Ord.compare`.\n"
    + "export union Ordering derives (Eq, Show) =\n"
    + "    | Less\n"
    + "    | Equal\n"
    + "    | Greater\n",
  "Option.hex":
    "// The canonical optional-value union used by total standard-library accessors.\n"
    + "export union Option(a) derives (Eq, Show) =\n"
    + "    | Some(value: a)\n"
    + "    | None\n",
  "Seq.hex":
    "(** A lazy, immutable, possibly infinite sequence of `a`s. Constructing a\n"
    + "    combinator computes nothing; each element is produced on demand by `next`,\n"
    + "    and produced again on every later traversal unless the sequence is\n"
    + "    `memoize`d. *)\n"
    + "(** Raised when a sequence position is forced while it is already being\n"
    + "    forced (FFI Part 3 section 7.3-7.4). *)\n"
    + "export exception ReentrancyError\n"
    + "\n"
    + "export opaque record Seq(+a) = { pull: () -> Option((a, Seq(a))) }\n"
    + "\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    (** Computes each element of `source` at most once however often the result\n"
    + "        is traversed, at the cost of retaining what has been produced. *)\n"
    + "    export fun seqMemoize as memoize<a>(source: Seq(a)): Seq(a)\n"
    + "\n"
    + "(** Drives one step: the head element and the successor sequence, or `None` when\n"
    + "    exhausted. `source` itself is unchanged. *)\n"
    + "export let next(source: Seq(a)): Option((a, Seq(a))) = (source.pull)()\n"
    + "\n"
    + "// Producers, and combinators whose step yields at most one element per pull.\n"
    + "\n"
    + "export let empty: Seq(a) = Seq({ pull = () => None })\n"
    + "\n"
    + "export let singleton(value: a): Seq(a) = Seq({ pull = () => Some((value, empty)) })\n"
    + "\n"
    + "(** The sequence that yields `value`, then everything in `rest`. *)\n"
    + "export let prepend(rest: Seq(a), value: a): Seq(a) = Seq({ pull = () => Some((value, rest)) })\n"
    + "\n"
    + "(** The infinite sequence `seed`, `step(seed)`, `step(step(seed))`, and so on.\n"
    + "    Bound it with `take` or `takeWhile` before consuming it. *)\n"
    + "export fun iterate(seed: a, step: a -> a): Seq(a) =\n"
    + "    Seq({ pull = () => Some((seed, iterate(step(seed), step))) })\n"
    + "\n"
    + "(** Applies `transform` to each element as that element is pulled. A traversal\n"
    + "    calls `transform` once per element, so two traversals call it twice —\n"
    + "    `memoize` the result when it is expensive. *)\n"
    + "export fun map(source: Seq(a), transform: a -> b): Seq(b) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) => Some((transform(value), map(rest, transform)))\n"
    + "    })\n"
    + "\n"
    + "(** The first `count` elements of `source`, or all of them if it is shorter. A\n"
    + "    `count` of zero or less gives the empty sequence. *)\n"
    + "export fun take(source: Seq(a), count: Int): Seq(a) =\n"
    + "    if count <= 0 then\n"
    + "        empty\n"
    + "    else\n"
    + "        Seq({ pull = () =>\n"
    + "            match next(source)\n"
    + "                None => None\n"
    + "                Some((value, rest)) => Some((value, take(rest, count - 1)))\n"
    + "        })\n"
    + "\n"
    + "(** The longest leading run of elements satisfying `keep`. The first element\n"
    + "    that fails ends the sequence and is not part of it. *)\n"
    + "export fun takeWhile(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) =>\n"
    + "                if keep(value) then\n"
    + "                    Some((value, takeWhile(rest, keep)))\n"
    + "                else\n"
    + "                    None\n"
    + "    })\n"
    + "\n"
    + "(** Grows a sequence from `seed`: each step produces one element and the seed\n"
    + "    for the next, and `None` ends it. The mirror of `fold`, which consumes one. *)\n"
    + "export fun unfold(seed: b, produce: b -> Option((a, b))): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match produce(seed)\n"
    + "            None => None\n"
    + "            Some((value, nextSeed)) => Some((value, unfold(nextSeed, produce)))\n"
    + "    })\n"
    + "\n"
    + "(** Combines elements pairwise with `combine`, ending as soon as either side\n"
    + "    runs out. *)\n"
    + "export fun zipWith(left: Seq(a), right: Seq(b), combine: (a, b) -> c): Seq(c) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(left)\n"
    + "            None => None\n"
    + "            Some((leftValue, leftRest)) =>\n"
    + "                match next(right)\n"
    + "                    None => None\n"
    + "                    Some((rightValue, rightRest)) =>\n"
    + "                        Some((combine(leftValue, rightValue), zipWith(leftRest, rightRest, combine)))\n"
    + "    })\n"
    + "\n"
    + "(** Pairs elements positionally, ending as soon as either side runs out. *)\n"
    + "export let zip(left: Seq(a), right: Seq(b)): Seq((a, b)) =\n"
    + "    zipWith(left, right, (leftValue, rightValue) => (leftValue, rightValue))\n"
    + "\n"
    + "(** The elements of `first`, then those of `second`. `second` is not pulled\n"
    + "    until `first` is exhausted, so an infinite `first` never reaches it. *)\n"
    + "export fun concat(first: Seq(a), second: Seq(a)): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(first)\n"
    + "            None => next(second)\n"
    + "            Some((value, rest)) => Some((value, concat(rest, second)))\n"
    + "    })\n"
    + "\n"
    + "// Combinators whose step may consume many source elements to yield one.\n"
    + "\n"
    + "(** The elements of `source` satisfying `keep`. One pull consumes source\n"
    + "    elements until it finds one, so pulling past the last match runs the source\n"
    + "    to exhaustion — and does not return at all if the source is infinite. *)\n"
    + "export fun filter(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := False\n"
    + "                Some((value, rest)) =>\n"
    + "                    if keep(value) then\n"
    + "                        result := Some((value, filter(rest, keep)))\n"
    + "                        searching := False\n"
    + "                    else\n"
    + "                        current := rest\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** `source` without its first `count` elements. They are skipped on the first\n"
    + "    pull of the result, not when `drop` is called. *)\n"
    + "export let drop(source: Seq(a), count: Int): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var remaining = count\n"
    + "        var result = None\n"
    + "        var running = True\n"
    + "        while running\n"
    + "            if remaining <= 0 then\n"
    + "                result := next(current)\n"
    + "                running := False\n"
    + "            else\n"
    + "                match next(current)\n"
    + "                    None => running := False\n"
    + "                    Some((_, rest)) =>\n"
    + "                        current := rest\n"
    + "                        remaining := remaining - 1\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** `source` from its first element that fails `discard` onward. Like `drop`,\n"
    + "    the skipping happens on the first pull of the result. *)\n"
    + "export let dropWhile(source: Seq(a), discard: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := False\n"
    + "                Some((value, rest)) =>\n"
    + "                    if discard(value) then\n"
    + "                        current := rest\n"
    + "                    else\n"
    + "                        result := Some((value, rest))\n"
    + "                        searching := False\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "// `flatMap` with the partially consumed inner sequence carried between pulls.\n"
    + "fun flatMapWith(source: Seq(a), transform: a -> Seq(b), pending: Seq(b)): Seq(b) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var outer = source\n"
    + "        var inner = pending\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(inner)\n"
    + "                Some((value, rest)) =>\n"
    + "                    result := Some((value, flatMapWith(outer, transform, rest)))\n"
    + "                    searching := False\n"
    + "                None =>\n"
    + "                    match next(outer)\n"
    + "                        None => searching := False\n"
    + "                        Some((outerValue, outerRest)) =>\n"
    + "                            outer := outerRest\n"
    + "                            inner := transform(outerValue)\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** The sequences `transform` produces, concatenated in order. Each is pulled to\n"
    + "    exhaustion before the next source element is read. *)\n"
    + "export let flatMap(source: Seq(a), transform: a -> Seq(b)): Seq(b) =\n"
    + "    flatMapWith(source, transform, empty)\n"
    + "\n"
    + "// Consumers: drive a `Seq` to a value.\n"
    + "\n"
    + "(** Reduces the whole sequence to one value, left to right, starting from\n"
    + "    `initial`. It pulls every element, so it does not return on an infinite\n"
    + "    sequence. *)\n"
    + "export let fold(source: Seq(a), initial: b, combine: (b, a) -> b): b =\n"
    + "    var accumulator = initial\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((value, rest)) =>\n"
    + "                accumulator := combine(accumulator, value)\n"
    + "                current := rest\n"
    + "    accumulator\n"
    + "\n"
    + "(** How many elements `source` yields. It pulls all of them, so it does not\n"
    + "    return on an infinite sequence. *)\n"
    + "export let length(source: Seq(a)): Int =\n"
    + "    var total = 0\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((_, rest)) =>\n"
    + "                total := total + 1\n"
    + "                current := rest\n"
    + "    total\n"
    + "\n"
    + "(** Runs `action` on each element in order, for its effect. It pulls the whole\n"
    + "    sequence, so it does not return on an infinite one. *)\n"
    + "export let forEach(source: Seq(a), action: a -> Unit): Unit =\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((value, rest)) =>\n"
    + "                action(value)\n"
    + "                current := rest\n"
    + "\n"
    + "(** The first element satisfying `matches`, or `None` if none does. It stops at\n"
    + "    that element, so it is safe on an infinite sequence that contains one. *)\n"
    + "export let find(source: Seq(a), matches: a -> Bool): Option(a) =\n"
    + "    var current = source\n"
    + "    var result = None\n"
    + "    var searching = True\n"
    + "    while searching\n"
    + "        match next(current)\n"
    + "            None => searching := False\n"
    + "            Some((value, rest)) =>\n"
    + "                if matches(value) then\n"
    + "                    result := Some(value)\n"
    + "                    searching := False\n"
    + "                else\n"
    + "                    current := rest\n"
    + "    result\n"
    + "\n"
    + "(** Whether any element satisfies `matches`, stopping at the first that does. *)\n"
    + "export let any(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    match find(source, matches)\n"
    + "        None => False\n"
    + "        Some(_) => True\n"
    + "\n"
    + "(** Whether every element satisfies `matches`, stopping at the first that does\n"
    + "    not. *)\n"
    + "export let all(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    not any(source, value => not matches(value))\n",
  "Result.hex":
    "// The canonical success-or-error union used across the standard library.\n"
    + "export union Result(a, e) =\n"
    + "    | Ok(value: a)\n"
    + "    | Err(error: e)\n",
};
