/**
 * Embedded copies of the canonical `stdlib/` prelude sources. Do not edit by hand.
 * Regenerate with `npm run generate:prelude`; a conformance test asserts these
 * never drift from the originals.
 */

export const PRELUDE_SOURCES: Readonly<Record<string, string>> = {
  "Show.hex":
    "(** The polymorphic face of textual rendering. Honoring `Show` gives a type one\n"
    + "    canonical textual form — the form string interpolation produces. *)\n"
    + "export constraint Show<a> =\n"
    + "    (** The canonical textual form of `value`. *)\n"
    + "    show(value: a): String\n",
  "Num.hex":
    "(** The polymorphic face of addition and multiplication. Honoring `Num` gives a\n"
    + "    type the `+` and `*` operators. *)\n"
    + "export constraint Num<a> =\n"
    + "    (** The sum of `left` and `right`. *)\n"
    + "    add(left: a, right: a): a\n"
    + "    (** The product of `left` and `right`. *)\n"
    + "    multiply(left: a, right: a): a\n"
    + "    (** The natural number `value` at this type. A bare non-negative literal\n"
    + "        reaches an instance through it. *)\n"
    + "    fromNat(value: Nat): a\n",
  "Signed.hex":
    "(** The polymorphic face of subtraction and sign. Honoring `Signed` gives a type\n"
    + "    the binary and unary `-` operators. *)\n"
    + "export constraint Signed<a: Num> =\n"
    + "    (** The difference of `left` and `right`. *)\n"
    + "    subtract(left: a, right: a): a\n"
    + "    (** The additive inverse of `value`. *)\n"
    + "    negate(value: a): a\n"
    + "    (** The integer `value` at this type. A bare negative literal reaches an\n"
    + "        instance through it. *)\n"
    + "    fromInt(value: Int): a\n",
  "Frac.hex":
    "(** The polymorphic face of division. Honoring `Frac` gives a type the `/`\n"
    + "    operator; the quotient is exact where the type is exact and rounded where\n"
    + "    it is not. *)\n"
    + "export constraint Frac<a: Signed> =\n"
    + "    (** `left` divided by `right`. *)\n"
    + "    divide(left: a, right: a): a\n",
  "Pow.hex":
    "(** Raised when an integer type is raised to a negative power, which has no\n"
    + "    answer at that type. `message` names the operation that threw. *)\n"
    + "export exception NegativeExponentError(message: String)\n"
    + "\n"
    + "(** The polymorphic face of exponentiation. Honoring `Pow` gives a type the `**`\n"
    + "    operator. *)\n"
    + "export constraint Pow<a: Num> =\n"
    + "    (** `left` raised to the power `right`. *)\n"
    + "    pow(left: a, right: a): a\n",
  "Concat.hex":
    "(** The polymorphic face of concatenation. Honoring `Concat` gives a type the\n"
    + "    `++` operator. *)\n"
    + "export constraint Concat<a> =\n"
    + "    (** `left` followed by `right`. *)\n"
    + "    concat(left: a, right: a): a\n",
  "Bool.hex":
    "// The boolean type. Constructor order `False | True` is normative: it is what makes\n"
    + "// the derived `Ord` order `False < True`.\n"
    + "export union Bool derives (Eq, Ord, Show, Hash) =\n"
    + "    | False\n"
    + "    | True\n",
  "Eq.hex":
    "(** The polymorphic face of equality. Honoring `Eq` gives a type the `==` and\n"
    + "    `!=` operators, and admits it as a component of a derived equality elsewhere. *)\n"
    + "export constraint Eq<a> =\n"
    + "    (** Whether `left` and `right` are equal. *)\n"
    + "    equals(left: a, right: a): Bool\n"
    + "    (** Whether `left` and `right` differ. An instance may override this for\n"
    + "        efficiency, but the override must equal the negation of `equals`. *)\n"
    + "    notEquals(left: a, right: a): Bool = not equals(left, right)\n",
  "Hash.hex":
    "(** The polymorphic face of hashing, and the key contract of the hash-backed\n"
    + "    collections. Instances are derived rather than hand-written, which is what\n"
    + "    keeps the law below true by construction. *)\n"
    + "export constraint Hash<a: Eq> =\n"
    + "    (** A hash of `value`. Equal values hash equally; unequal values may collide,\n"
    + "        and the hash is not resistant to an adversary choosing them. *)\n"
    + "    hash(value: a): Int\n",
  "Prelude.hex":
    "// The outcome of comparing two values, as produced by `Ord.compare`.\n"
    + "export union Ordering derives (Eq, Show) =\n"
    + "    | Less\n"
    + "    | Equal\n"
    + "    | Greater\n",
  "Ord.hex":
    "(** The polymorphic face of ordering. Honoring `Ord` gives a type the `<`, `<=`,\n"
    + "    `>`, and `>=` operators. *)\n"
    + "export constraint Ord<a: Eq> =\n"
    + "    (** How `left` orders against `right`. *)\n"
    + "    compare(left: a, right: a): Ordering\n",
  "Integral.hex":
    "(** Raised when a division or remainder is asked for with a zero divisor, at any\n"
    + "    integer type. `message` names the operation that threw. *)\n"
    + "export exception DivideByZeroError(message: String)\n"
    + "\n"
    + "(** The polymorphic face of exact integer division. Honoring `Integral` gives a\n"
    + "    type both division conventions — Euclidean `div`/`mod` and truncated\n"
    + "    `quot`/`rem` — along with greatest common divisors. *)\n"
    + "export constraint Integral<a: (Num, Ord)> =\n"
    + "    (** The Euclidean quotient of `left` divided by `right`. *)\n"
    + "    div(left: a, right: a): a\n"
    + "    (** The Euclidean remainder of `left` divided by `right`, always in\n"
    + "        `[0, abs(right))` whatever the signs. *)\n"
    + "    mod(left: a, right: a): a\n"
    + "    (** The truncated quotient of `left` divided by `right`, rounding toward\n"
    + "        zero. *)\n"
    + "    quot(left: a, right: a): a\n"
    + "    (** The truncated remainder of `left` divided by `right`, taking the sign of\n"
    + "        `left`. *)\n"
    + "    rem(left: a, right: a): a\n"
    + "    (** The greatest common divisor of `left` and `right`, never negative. *)\n"
    + "    gcd(left: a, right: a): a\n",
  "Option.hex":
    "// The canonical optional-value union used by total standard-library accessors.\n"
    + "export union Option(a) derives (Eq, Show) =\n"
    + "    | Some(value: a)\n"
    + "    | None\n",
  "BigInt.hex":
    "// The public `BigInt` companion. A primitive's home module is its fixed prelude\n"
    + "// companion (Constraints §5.3), so this file is where `BigInt`'s instances are\n"
    + "// declared and where the orphan rule lets them be declared.\n"
    + "\n"
    + "// The natives, and only the natives. An own-operation member body cannot be\n"
    + "// written in operators or interpolation — that sugar selects the very slot being\n"
    + "// defined (Constraints §6.1) — so every such member is a one-line delegation to\n"
    + "// one of the declarations below. Everything expressible over strictly simpler\n"
    + "// operations is ordinary Hexagon further down: the Euclidean pair over the\n"
    + "// truncated one, `gcd`'s loop over `rem`, `lcm` over `gcd`, and every guard.\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    fun bigIntAdd as nativeAdd(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntMultiply as nativeMultiply(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntFromNat as nativeFromNat(value: Nat): BigInt\n"
    + "    fun bigIntSubtract as nativeSubtract(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntNegate as nativeNegate(value: BigInt): BigInt\n"
    + "    fun bigIntFromInt as nativeFromInt(value: Int): BigInt\n"
    + "    fun bigIntEquals as nativeEquals(left: BigInt, right: BigInt): Bool\n"
    + "    fun bigIntCompare as nativeCompare(left: BigInt, right: BigInt): Ordering\n"
    + "    fun bigIntShow as nativeShow(value: BigInt): String\n"
    + "    fun bigIntPow as nativePow(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntHash as nativeHash(value: BigInt): Int\n"
    + "    fun bigIntQuot as nativeQuot(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntRem as nativeRem(left: BigInt, right: BigInt): BigInt\n"
    + "    fun bigIntToIntUnchecked as toIntUnchecked(value: BigInt): Int\n"
    + "\n"
    + "    (** `value` as the nearest `Float`. Total and lossy: a magnitude past 2^53\n"
    + "        rounds, and one past `Float`'s range becomes an infinity. *)\n"
    + "    export fun bigIntToFloat as toFloat(value: BigInt): Float\n"
    + "\n"
    + "honor Num<BigInt> =\n"
    + "    (** The sum of `left` and `right`, exactly. *)\n"
    + "    add(left, right) = nativeAdd(left, right)\n"
    + "    (** The product of `left` and `right`, exactly. *)\n"
    + "    multiply(left, right) = nativeMultiply(left, right)\n"
    + "    (** The natural number `value` as a `BigInt`. Total and exact. *)\n"
    + "    fromNat(value) = nativeFromNat(value)\n"
    + "\n"
    + "honor Signed<BigInt> =\n"
    + "    (** The difference of `left` and `right`, exactly. *)\n"
    + "    subtract(left, right) = nativeSubtract(left, right)\n"
    + "    (** The additive inverse of `value`. *)\n"
    + "    negate(value) = nativeNegate(value)\n"
    + "    (** The integer `value` as a `BigInt`. Total and exact — every `Int` is a\n"
    + "        `BigInt`. *)\n"
    + "    fromInt(value) = nativeFromInt(value)\n"
    + "\n"
    + "honor Eq<BigInt> =\n"
    + "    (** Whether `left` and `right` are the same integer. *)\n"
    + "    equals(left, right) = nativeEquals(left, right)\n"
    + "\n"
    + "honor Ord<BigInt> =\n"
    + "    (** How `left` orders against `right`, by numeric value. *)\n"
    + "    compare(left, right) = nativeCompare(left, right)\n"
    + "\n"
    + "honor Show<BigInt> =\n"
    + "    (** The decimal form of `value`, with no `n` suffix — `1n` shows as `1`. *)\n"
    + "    show(value) = nativeShow(value)\n"
    + "\n"
    + "honor Pow<BigInt> =\n"
    + "    (** `left` raised to the power `right`, exactly. Raises\n"
    + "        `NegativeExponentError` when `right` is negative: a negative power of an\n"
    + "        integer is not an integer. *)\n"
    + "    pow(left, right) =\n"
    + "        if right < 0 then\n"
    + "            throw(NegativeExponentError(\"an integer exponent cannot be negative\"))\n"
    + "        else\n"
    + "            nativePow(left, right)\n"
    + "\n"
    + "honor Hash<BigInt> =\n"
    + "    (** A hash of `value`. Equal `BigInt`s hash equally, which is what `Eq` above\n"
    + "        is checked against. *)\n"
    + "    hash(value) = nativeHash(value)\n"
    + "\n"
    + "honor Integral<BigInt> =\n"
    + "    (** The truncated quotient of `left` divided by `right`, rounding toward\n"
    + "        zero. Raises `DivideByZeroError` when `right` is zero. *)\n"
    + "    quot(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"BigInt.quot: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeQuot(left, right)\n"
    + "\n"
    + "    (** The truncated remainder of `left` divided by `right`, taking the sign of\n"
    + "        `left` — this is JS's `%`. Raises `DivideByZeroError` when `right` is\n"
    + "        zero, where JS would answer `NaN` or throw a `RangeError`. *)\n"
    + "    rem(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"BigInt.rem: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeRem(left, right)\n"
    + "\n"
    + "    (** The Euclidean remainder of `left` divided by `right`: always\n"
    + "        non-negative, whatever the signs. Raises `DivideByZeroError` when\n"
    + "        `right` is zero. *)\n"
    + "    mod(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"BigInt.mod: divisor is zero\"))\n"
    + "        else\n"
    + "            let remainder = rem(left, right)\n"
    + "            if remainder < 0 then\n"
    + "                remainder + (if right < 0 then -right else right)\n"
    + "            else\n"
    + "                remainder\n"
    + "\n"
    + "    (** The Euclidean quotient of `left` divided by `right`: the unique partner\n"
    + "        of `mod` satisfying `div(l, r) * r + mod(l, r) == l`. Raises\n"
    + "        `DivideByZeroError` when `right` is zero. *)\n"
    + "    div(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"BigInt.div: divisor is zero\"))\n"
    + "        else\n"
    + "            quot(left - mod(left, right), right)\n"
    + "\n"
    + "    (** The greatest common divisor of `left` and `right`, never negative.\n"
    + "        `gcd(value, 0)` is the magnitude of `value`, so `gcd(0, 0)` is zero; it\n"
    + "        never throws. *)\n"
    + "    gcd(left, right) =\n"
    + "        var larger = if left < 0 then -left else left\n"
    + "        var smaller = if right < 0 then -right else right\n"
    + "        // Both operands are non-negative from here, so the loop's `rem` never\n"
    + "        // sees a zero divisor: a zero `smaller` is the exit condition.\n"
    + "        while smaller != 0\n"
    + "            let next = rem(larger, smaller)\n"
    + "            larger := smaller\n"
    + "            smaller := next\n"
    + "        larger\n"
    + "\n"
    + "// The largest magnitude an `Int` holds exactly: 2^53 - 1.\n"
    + "let intLimit: BigInt = 9_007_199_254_740_991n\n"
    + "\n"
    + "(** The least common multiple of `left` and `right`, never negative. It is zero\n"
    + "    when either operand is, and never throws. Dividing before multiplying keeps\n"
    + "    the intermediate small and is the form to copy at a fixed-width type. *)\n"
    + "export let lcm(left: BigInt, right: BigInt): BigInt =\n"
    + "    if left == 0 or right == 0 then\n"
    + "        0\n"
    + "    else\n"
    + "        let multiple = quot(left, gcd(left, right)) * right\n"
    + "        if multiple < 0 then -multiple else multiple\n"
    + "\n"
    + "(** `value` as an `Int`, or `None` when its magnitude is past the range an `Int`\n"
    + "    holds exactly. The total direction is `BigInt.fromInt`. *)\n"
    + "export let toInt(value: BigInt): Option(Int) =\n"
    + "    if value < -intLimit or value > intLimit then\n"
    + "        None\n"
    + "    else\n"
    + "        Some(toIntUnchecked(value))\n",
  "Int.hex":
    "// The public `Int` companion. A primitive's home module is its fixed prelude\n"
    + "// companion (Constraints §5.3), so this file is where `Int`'s instances are\n"
    + "// declared and where the orphan rule lets them be declared.\n"
    + "\n"
    + "// The natives, and only the natives. An own-operation member body cannot be\n"
    + "// written in operators or interpolation — that sugar selects the very slot being\n"
    + "// defined (Constraints §6.1) — so every such member is a one-line delegation to\n"
    + "// one of the declarations below. Everything expressible over strictly simpler\n"
    + "// operations is ordinary Hexagon further down: the Euclidean pair over the\n"
    + "// truncated one, `gcd`'s loop over `rem`, the checked family's pre-checks, and\n"
    + "// every guard.\n"
    + "//\n"
    + "// Two members are absent from this block on purpose. `Signed<Int>`'s `fromInt`\n"
    + "// converts `Int` to itself, so its body is the plain binding `value` — no\n"
    + "// operator, no interpolation, no widening, nothing that selects its own slot —\n"
    + "// and the strictly-simpler doctrine sends such a body to ordinary Hexagon\n"
    + "// (`spec/intrinsics.md` §3.2). `intFromNat` does cross: any Hexagon body for\n"
    + "// `Nat` -> `Int` typechecks only through Numeric Literals §5.1's contextual\n"
    + "// widening, which elaborates through `Num<Int>.fromNat`, the very slot being\n"
    + "// defined.\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    fun intAdd as nativeAdd(left: Int, right: Int): Int\n"
    + "    fun intMultiply as nativeMultiply(left: Int, right: Int): Int\n"
    + "    fun intFromNat as nativeFromNat(value: Nat): Int\n"
    + "    fun intSubtract as nativeSubtract(left: Int, right: Int): Int\n"
    + "    fun intNegate as nativeNegate(value: Int): Int\n"
    + "    fun intEquals as nativeEquals(left: Int, right: Int): Bool\n"
    + "    fun intCompare as nativeCompare(left: Int, right: Int): Ordering\n"
    + "    fun intShow as nativeShow(value: Int): String\n"
    + "    fun intPow as nativePow(left: Int, right: Int): Int\n"
    + "    fun intHash as nativeHash(value: Int): Int\n"
    + "    fun intQuot as nativeQuot(left: Int, right: Int): Int\n"
    + "    fun intRem as nativeRem(left: Int, right: Int): Int\n"
    + "\n"
    + "honor Num<Int> =\n"
    + "    (** The sum of `left` and `right`, exact within the safe range. *)\n"
    + "    add(left, right) = nativeAdd(left, right)\n"
    + "    (** The product of `left` and `right`, exact within the safe range. *)\n"
    + "    multiply(left, right) = nativeMultiply(left, right)\n"
    + "    (** The natural number `value` as an `Int`. Total: every `Nat` is an `Int`. *)\n"
    + "    fromNat(value) = nativeFromNat(value)\n"
    + "\n"
    + "honor Signed<Int> =\n"
    + "    (** The difference of `left` and `right`, exact within the safe range. *)\n"
    + "    subtract(left, right) = nativeSubtract(left, right)\n"
    + "    (** The additive inverse of `value`. Total: the safe range is symmetric. *)\n"
    + "    negate(value) = nativeNegate(value)\n"
    + "    (** The integer `value` as an `Int`, which is `value` itself. *)\n"
    + "    fromInt(value) = value\n"
    + "\n"
    + "honor Eq<Int> =\n"
    + "    (** Whether `left` and `right` are the same integer. *)\n"
    + "    equals(left, right) = nativeEquals(left, right)\n"
    + "\n"
    + "honor Ord<Int> =\n"
    + "    (** How `left` orders against `right`, by numeric value. *)\n"
    + "    compare(left, right) = nativeCompare(left, right)\n"
    + "\n"
    + "honor Show<Int> =\n"
    + "    (** The decimal form of `value`, with a leading `-` when it is negative. *)\n"
    + "    show(value) = nativeShow(value)\n"
    + "\n"
    + "honor Pow<Int> =\n"
    + "    (** `left` raised to the power `right`. Raises `NegativeExponentError` when\n"
    + "        `right` is negative: a negative power of an integer is not an integer. *)\n"
    + "    pow(left, right) =\n"
    + "        if right < 0 then\n"
    + "            throw(NegativeExponentError(\"an integer exponent cannot be negative\"))\n"
    + "        else\n"
    + "            nativePow(left, right)\n"
    + "\n"
    + "honor Hash<Int> =\n"
    + "    (** A hash of `value`. Equal `Int`s hash equally, which is what `Eq` above\n"
    + "        is checked against. *)\n"
    + "    hash(value) = nativeHash(value)\n"
    + "\n"
    + "honor Integral<Int> =\n"
    + "    (** The truncated quotient of `left` divided by `right`, rounding toward\n"
    + "        zero. Raises `DivideByZeroError` when `right` is zero. *)\n"
    + "    quot(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Int.quot: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeQuot(left, right)\n"
    + "\n"
    + "    (** The truncated remainder of `left` divided by `right`, taking the sign of\n"
    + "        `left` — this is JS's `%`. Raises `DivideByZeroError` when `right` is\n"
    + "        zero, where JS would answer `NaN`. *)\n"
    + "    rem(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Int.rem: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeRem(left, right)\n"
    + "\n"
    + "    (** The Euclidean remainder of `left` divided by `right`: always\n"
    + "        non-negative, whatever the signs. Raises `DivideByZeroError` when\n"
    + "        `right` is zero. *)\n"
    + "    mod(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Int.mod: divisor is zero\"))\n"
    + "        else\n"
    + "            let remainder = rem(left, right)\n"
    + "            if remainder < 0 then\n"
    + "                remainder + (if right < 0 then -right else right)\n"
    + "            else\n"
    + "                remainder\n"
    + "\n"
    + "    (** The Euclidean quotient of `left` divided by `right`: the unique partner\n"
    + "        of `mod` satisfying `div(l, r) * r + mod(l, r) == l`. Raises\n"
    + "        `DivideByZeroError` when `right` is zero. *)\n"
    + "    div(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Int.div: divisor is zero\"))\n"
    + "        else\n"
    + "            quot(left - mod(left, right), right)\n"
    + "\n"
    + "    (** The greatest common divisor of `left` and `right`, never negative.\n"
    + "        `gcd(value, 0)` is the magnitude of `value`, so `gcd(0, 0)` is zero; it\n"
    + "        never throws. *)\n"
    + "    gcd(left, right) =\n"
    + "        var larger = if left < 0 then -left else left\n"
    + "        var smaller = if right < 0 then -right else right\n"
    + "        // Both operands are non-negative from here, so the loop's `rem` never\n"
    + "        // sees a zero divisor: a zero `smaller` is the exit condition.\n"
    + "        while smaller != 0\n"
    + "            let next = rem(larger, smaller)\n"
    + "            larger := smaller\n"
    + "            smaller := next\n"
    + "        larger\n"
    + "\n"
    + "// The largest magnitude an `Int` holds exactly, in either direction: 2^53 - 1.\n"
    + "// The range being symmetric is what lets `checkedSub` negate its right operand\n"
    + "// and hand the result to `checkedAdd`.\n"
    + "let intLimit: Int = 9_007_199_254_740_991\n"
    + "\n"
    + "(** The sum of `left` and `right`, or `None` when it would leave the range an\n"
    + "    `Int` holds exactly. The test is a pre-check, so no intermediate here ever\n"
    + "    leaves that range (Primitive Types §2.1). *)\n"
    + "export let checkedAdd(left: Int, right: Int): Option(Int) =\n"
    + "    if right > 0 and left > intLimit - right then\n"
    + "        None\n"
    + "    else if right < 0 and left < -intLimit - right then\n"
    + "        None\n"
    + "    else\n"
    + "        Some(left + right)\n"
    + "\n"
    + "(** The difference of `left` and `right`, or `None` when it would leave the\n"
    + "    range an `Int` holds exactly. Negating `right` is total on that symmetric\n"
    + "    range, so this is the sum with the sign turned around. *)\n"
    + "export let checkedSub(left: Int, right: Int): Option(Int) =\n"
    + "    checkedAdd(left, -right)\n"
    + "\n"
    + "(** The product of `left` and `right`, or `None` when it would leave the range\n"
    + "    an `Int` holds exactly. The magnitudes are compared before multiplying,\n"
    + "    because an oversized product rounds before any check could see it. *)\n"
    + "export let checkedMul(left: Int, right: Int): Option(Int) =\n"
    + "    if left == 0 or right == 0 then\n"
    + "        Some(0)\n"
    + "    else\n"
    + "        let leftMagnitude = if left < 0 then -left else left\n"
    + "        let rightMagnitude = if right < 0 then -right else right\n"
    + "        if leftMagnitude > quot(intLimit, rightMagnitude) then\n"
    + "            None\n"
    + "        else\n"
    + "            Some(left * right)\n",
  "Nat.hex":
    "// The public `Nat` companion. A primitive's home module is its fixed prelude\n"
    + "// companion (Constraints §5.3), so this file is where `Nat`'s instances are\n"
    + "// declared and where the orphan rule lets them be declared.\n"
    + "\n"
    + "// The natives, and only the natives. An own-operation member body cannot be\n"
    + "// written in operators or interpolation — that sugar selects the very slot being\n"
    + "// defined (Constraints §6.1) — so every such member is a one-line delegation to\n"
    + "// one of the declarations below. Everything expressible over strictly simpler\n"
    + "// operations is ordinary Hexagon further down: `gcd`'s loop over `rem`,\n"
    + "// `fromInt`'s sign check, and every zero-divisor guard.\n"
    + "//\n"
    + "// `Num<Nat>`'s `fromNat` is absent from this block on purpose: it converts `Nat`\n"
    + "// to itself, so its body is the plain binding `value` — no operator, no\n"
    + "// interpolation, no widening, nothing that selects its own slot — and the\n"
    + "// strictly-simpler doctrine sends such a body to ordinary Hexagon\n"
    + "// (`spec/intrinsics.md` §3.2).\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    fun natAdd as nativeAdd(left: Nat, right: Nat): Nat\n"
    + "    fun natMultiply as nativeMultiply(left: Nat, right: Nat): Nat\n"
    + "    fun natEquals as nativeEquals(left: Nat, right: Nat): Bool\n"
    + "    fun natCompare as nativeCompare(left: Nat, right: Nat): Ordering\n"
    + "    fun natShow as nativeShow(value: Nat): String\n"
    + "    fun natPow as nativePow(left: Nat, right: Nat): Nat\n"
    + "    fun natHash as nativeHash(value: Nat): Int\n"
    + "    fun natQuot as nativeQuot(left: Nat, right: Nat): Nat\n"
    + "    fun natRem as nativeRem(left: Nat, right: Nat): Nat\n"
    + "    fun natFromIntUnchecked as fromIntUnchecked(value: Int): Nat\n"
    + "\n"
    + "honor Num<Nat> =\n"
    + "    (** The sum of `left` and `right`, exact within the safe range. *)\n"
    + "    add(left, right) = nativeAdd(left, right)\n"
    + "    (** The product of `left` and `right`, exact within the safe range. *)\n"
    + "    multiply(left, right) = nativeMultiply(left, right)\n"
    + "    (** The natural number `value` as a `Nat`, which is `value` itself. *)\n"
    + "    fromNat(value) = value\n"
    + "\n"
    + "honor Eq<Nat> =\n"
    + "    (** Whether `left` and `right` are the same natural number. *)\n"
    + "    equals(left, right) = nativeEquals(left, right)\n"
    + "\n"
    + "honor Ord<Nat> =\n"
    + "    (** How `left` orders against `right`, by numeric value. *)\n"
    + "    compare(left, right) = nativeCompare(left, right)\n"
    + "\n"
    + "honor Show<Nat> =\n"
    + "    (** The decimal form of `value`, which never carries a sign. *)\n"
    + "    show(value) = nativeShow(value)\n"
    + "\n"
    + "honor Pow<Nat> =\n"
    + "    (** `left` raised to the power `right`. It never throws: the guard `Int` and\n"
    + "        `BigInt` carry is dead here, because a `Nat` exponent cannot be\n"
    + "        negative. *)\n"
    + "    pow(left, right) = nativePow(left, right)\n"
    + "\n"
    + "honor Hash<Nat> =\n"
    + "    (** A hash of `value`. Equal `Nat`s hash equally, which is what `Eq` above\n"
    + "        is checked against. *)\n"
    + "    hash(value) = nativeHash(value)\n"
    + "\n"
    + "honor Integral<Nat> =\n"
    + "    (** The truncated quotient of `left` divided by `right`, which at `Nat` is\n"
    + "        the Euclidean one. Raises `DivideByZeroError` when `right` is zero. *)\n"
    + "    quot(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Nat.quot: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeQuot(left, right)\n"
    + "\n"
    + "    (** The truncated remainder of `left` divided by `right`, which at `Nat` is\n"
    + "        the Euclidean one. Raises `DivideByZeroError` when `right` is zero. *)\n"
    + "    rem(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Nat.rem: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeRem(left, right)\n"
    + "\n"
    + "    (** The Euclidean remainder of `left` divided by `right`. Neither operand\n"
    + "        can be negative, so it is the truncated remainder value for value, and\n"
    + "        it carries its own guard so a zero divisor names this member. Raises\n"
    + "        `DivideByZeroError` when `right` is zero. *)\n"
    + "    mod(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Nat.mod: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeRem(left, right)\n"
    + "\n"
    + "    (** The Euclidean quotient of `left` divided by `right`, equal to the\n"
    + "        truncated quotient at this type and guarded in its own name. Raises\n"
    + "        `DivideByZeroError` when `right` is zero. *)\n"
    + "    div(left, right) =\n"
    + "        if right == 0 then\n"
    + "            throw(DivideByZeroError(\"Nat.div: divisor is zero\"))\n"
    + "        else\n"
    + "            nativeQuot(left, right)\n"
    + "\n"
    + "    (** The greatest common divisor of `left` and `right`. `gcd(value, 0)` is\n"
    + "        `value`, so `gcd(0, 0)` is zero; it never throws. *)\n"
    + "    gcd(left, right) =\n"
    + "        var larger = left\n"
    + "        var smaller = right\n"
    + "        // Both operands are non-negative by their type, so the loop's `rem`\n"
    + "        // never sees a zero divisor: a zero `smaller` is the exit condition.\n"
    + "        while smaller != 0\n"
    + "            let next = rem(larger, smaller)\n"
    + "            larger := smaller\n"
    + "            smaller := next\n"
    + "        larger\n"
    + "\n"
    + "(** The integer `value` as a `Nat`, or `None` when it is negative. The total\n"
    + "    direction is `Num.fromNat`, which widens an established `Nat` into any\n"
    + "    numeric type. *)\n"
    + "export let fromInt(value: Int): Option(Nat) =\n"
    + "    if value < 0 then\n"
    + "        None\n"
    + "    else\n"
    + "        Some(fromIntUnchecked(value))\n",
  "Float.hex":
    "// The public `Float` companion. A primitive's home module is its fixed prelude\n"
    + "// companion (Constraints §5.3), so this file is where `Float`'s instances are\n"
    + "// declared and where the orphan rule lets them be declared.\n"
    + "\n"
    + "// The natives, and only the natives. An own-operation member body cannot be\n"
    + "// written in operators or interpolation — that sugar selects the very slot being\n"
    + "// defined (Constraints §6.1) — so every such member is a one-line delegation to\n"
    + "// one of the declarations below. The one thing above the door here is `mod`, the\n"
    + "// Euclidean adjustment over `rem`; there is no guard anywhere in this file,\n"
    + "// because float partiality is `NaN` rather than a throw.\n"
    + "//\n"
    + "// `Num<Float>`'s `fromNat` is absent from this block on purpose: it composes out\n"
    + "// of two slots that already exist beneath it — `Signed.fromInt` over\n"
    + "// `Int.fromNat`, each piece exact, total, and a different slot than the one\n"
    + "// being defined — and the strictly-simpler doctrine sends such a body to\n"
    + "// ordinary Hexagon (`spec/intrinsics.md` §3.2). The conversion is reached\n"
    + "// through its declaring module rather than bare because bare `fromInt` has two\n"
    + "// exporters and is refused (Modules §5.5 — `Signed.hex`'s member and\n"
    + "// `Nat.hex`'s function, the regression ratified with the second landing); the\n"
    + "// `Signed` block is written above the `Num` block anyway, so a reader meets\n"
    + "// the composition's pieces in the order it uses them. `floatFromInt` *does*\n"
    + "// cross: any Hexagon body for `Int` -> `Float` typechecks only through Numeric\n"
    + "// Literals §5.1's contextual widening, which elaborates through\n"
    + "// `Signed<Float>`'s `fromInt`, the very slot being defined.\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    fun floatAdd as nativeAdd(left: Float, right: Float): Float\n"
    + "    fun floatMultiply as nativeMultiply(left: Float, right: Float): Float\n"
    + "    fun floatSubtract as nativeSubtract(left: Float, right: Float): Float\n"
    + "    fun floatNegate as nativeNegate(value: Float): Float\n"
    + "    fun floatFromInt as nativeFromInt(value: Int): Float\n"
    + "    fun floatDivide as nativeDivide(left: Float, right: Float): Float\n"
    + "    fun floatEquals as nativeEquals(left: Float, right: Float): Bool\n"
    + "    fun floatCompare as nativeCompare(left: Float, right: Float): Ordering\n"
    + "    fun floatShow as nativeShow(value: Float): String\n"
    + "    fun floatPow as nativePow(left: Float, right: Float): Float\n"
    + "    fun floatHash as nativeHash(value: Float): Int\n"
    + "\n"
    + "    (** The truncated remainder of `left` divided by `right`, taking the sign of\n"
    + "        `left` — this is JS's `%`, and C's `fmod`. It is exact: the true\n"
    + "        remainder of two floats is always a float, so nothing rounds. It never\n"
    + "        throws; a zero divisor or a non-finite operand answers `NaN`, exactly as\n"
    + "        float division does. *)\n"
    + "    export fun floatRem as rem(left: Float, right: Float): Float\n"
    + "\n"
    + "honor Eq<Float> =\n"
    + "    (** Whether `left` and `right` are the same float, by SameValueZero: `NaN`\n"
    + "        equals itself and `-0.0` equals `0.0`. This is deliberately not the\n"
    + "        host's `===`, so that a float can key a hash table. *)\n"
    + "    equals(left, right) = nativeEquals(left, right)\n"
    + "\n"
    + "honor Ord<Float> =\n"
    + "    (** How `left` orders against `right`: a total order, so every float has a\n"
    + "        place. `NaN` sorts last, after `+Infinity`, and `-0.0` compares equal to\n"
    + "        `0.0`. *)\n"
    + "    compare(left, right) = nativeCompare(left, right)\n"
    + "\n"
    + "honor Show<Float> =\n"
    + "    (** The host's decimal form of `value`, warts and all: `4.0` shows as `4`,\n"
    + "        `-0.0` as `0`, and the non-finite floats as `NaN`, `Infinity`, and\n"
    + "        `-Infinity`. *)\n"
    + "    show(value) = nativeShow(value)\n"
    + "\n"
    + "honor Hash<Float> =\n"
    + "    (** A hash of `value`, normalized to agree with `Eq` above: every `NaN`\n"
    + "        hashes alike, and `-0.0` hashes as `0.0`. *)\n"
    + "    hash(value) = nativeHash(value)\n"
    + "\n"
    + "honor Signed<Float> =\n"
    + "    (** The difference of `left` and `right`, rounded to the nearest float. *)\n"
    + "    subtract(left, right) = nativeSubtract(left, right)\n"
    + "    (** The additive inverse of `value`. Total, and it does distinguish the\n"
    + "        zeroes: negating `0.0` gives `-0.0`. *)\n"
    + "    negate(value) = nativeNegate(value)\n"
    + "    (** The integer `value` as a `Float`. Total and exact: the range an `Int`\n"
    + "        holds is exactly the range a float holds without rounding. *)\n"
    + "    fromInt(value) = nativeFromInt(value)\n"
    + "\n"
    + "honor Num<Float> =\n"
    + "    (** The sum of `left` and `right`, rounded to the nearest float. *)\n"
    + "    add(left, right) = nativeAdd(left, right)\n"
    + "    (** The product of `left` and `right`, rounded to the nearest float. *)\n"
    + "    multiply(left, right) = nativeMultiply(left, right)\n"
    + "    (** The natural number `value` as a `Float`, through the two conversions\n"
    + "        beneath it: every `Nat` is an `Int`, and every `Int` is a `Float`. *)\n"
    + "    fromNat(value) = Signed.fromInt(Int.fromNat(value))\n"
    + "\n"
    + "honor Frac<Float> =\n"
    + "    (** `left` divided by `right`, following IEEE 754. It never throws: a zero\n"
    + "        divisor answers an infinity, or `NaN` when the dividend is zero too. *)\n"
    + "    divide(left, right) = nativeDivide(left, right)\n"
    + "\n"
    + "honor Pow<Float> =\n"
    + "    (** `left` raised to the power `right`. It never throws: a negative float\n"
    + "        exponent is an ordinary float operation, so the guard the integer types\n"
    + "        carry does not exist here. *)\n"
    + "    pow(left, right) = nativePow(left, right)\n"
    + "\n"
    + "(** The Euclidean remainder of `left` divided by `right`: never negative,\n"
    + "    whatever the signs — which is what angle wrapping, phase accumulation, and\n"
    + "    hue rotation want. It never throws, answering `NaN` wherever `rem` does. One\n"
    + "    honest caveat at this type: the adjustment that lifts a negative remainder\n"
    + "    can round up to the magnitude of `right` itself when the remainder is tiny\n"
    + "    and the divisor is large, so the bound is `0.0 <= result <= abs(right)`\n"
    + "    rather than the strict one `Int.mod` keeps. *)\n"
    + "export let mod(left: Float, right: Float): Float =\n"
    + "    let remainder = rem(left, right)\n"
    + "    if remainder < 0.0 then\n"
    + "        remainder + (if right < 0.0 then -right else right)\n"
    + "    else\n"
    + "        remainder\n",
  "String.hex":
    "// The public `String` companion. A primitive's home module is its fixed prelude\n"
    + "// companion (Constraints §5.3), so this file is where `String`'s instances are\n"
    + "// declared and where the orphan rule lets them be declared.\n"
    + "\n"
    + "// The natives, and only the natives. An own-operation member body cannot be\n"
    + "// written in operators or interpolation — that sugar selects the very slot being\n"
    + "// defined (Constraints §6.1) — so every such member is a one-line delegation to\n"
    + "// one of the declarations below. `compare` is here for a second reason as well:\n"
    + "// its codepoint walk has no strictly simpler Hexagon to be written in, because\n"
    + "// the language has no codepoint API.\n"
    + "//\n"
    + "// `Show<String>`'s `show` is absent from this block on purpose: it is the\n"
    + "// identity by ruling (Primitive Types §7), so its body is the plain binding\n"
    + "// `value` — no operator, no interpolation, nothing that selects its own slot —\n"
    + "// and the strictly-simpler doctrine sends such a body to ordinary Hexagon\n"
    + "// (`spec/intrinsics.md` §3.2). Everything a string's *contents* can be asked —\n"
    + "// length, slicing, joining — belongs to the listing and collections surfaces,\n"
    + "// not here.\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    fun stringConcat as nativeConcat(left: String, right: String): String\n"
    + "    fun stringEquals as nativeEquals(left: String, right: String): Bool\n"
    + "    fun stringCompare as nativeCompare(left: String, right: String): Ordering\n"
    + "    fun stringHash as nativeHash(value: String): Int\n"
    + "\n"
    + "honor Eq<String> =\n"
    + "    (** Whether `left` and `right` are the same text. *)\n"
    + "    equals(left, right) = nativeEquals(left, right)\n"
    + "\n"
    + "honor Ord<String> =\n"
    + "    (** How `left` orders against `right`, by Unicode code point. An astral\n"
    + "        character therefore orders after every character of the basic plane,\n"
    + "        which is where a host's own string comparison disagrees. *)\n"
    + "    compare(left, right) = nativeCompare(left, right)\n"
    + "\n"
    + "honor Show<String> =\n"
    + "    (** `value` itself: a string's canonical textual form is the string, with no\n"
    + "        quoting and no escaping. *)\n"
    + "    show(value) = value\n"
    + "\n"
    + "honor Concat<String> =\n"
    + "    (** `left` followed by `right`. *)\n"
    + "    concat(left, right) = nativeConcat(left, right)\n"
    + "\n"
    + "honor Hash<String> =\n"
    + "    (** A hash of `value`. Equal strings hash equally, which is what `Eq` above\n"
    + "        is checked against. *)\n"
    + "    hash(value) = nativeHash(value)\n",
  "Seq.hex":
    "(** A lazy, immutable, possibly infinite sequence of `a`s. Constructing a\n"
    + "    combinator computes nothing; each element is produced on demand by `next`,\n"
    + "    and produced again on every later traversal unless the sequence is\n"
    + "    `memoize`d. *)\n"
    + "(** Raised when a sequence position is forced while it is already being\n"
    + "    forced (FFI Part 3 section 7.3-7.4). *)\n"
    + "export exception ReentrancyError\n"
    + "\n"
    + "export opaque record Seq(+a) = { pull: () -> Option((a, Seq(a))) }\n"
    + "\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    (** Computes each element of `source` at most once however often the result\n"
    + "        is traversed, at the cost of retaining what has been produced. *)\n"
    + "    export fun seqMemoize as memoize(source: Seq(a)): Seq(a)\n"
    + "\n"
    + "(** Drives one step: the head element and the successor sequence, or `None` when\n"
    + "    exhausted. `source` itself is unchanged. *)\n"
    + "export let next(source: Seq(a)): Option((a, Seq(a))) = (source.pull)()\n"
    + "\n"
    + "// Producers, and combinators whose step yields at most one element per pull.\n"
    + "\n"
    + "(** The empty sequence. *)\n"
    + "export let empty: Seq(a) = Seq({ pull = () => None })\n"
    + "\n"
    + "(** A sequence with a single value. *)\n"
    + "export let singleton(value: a): Seq(a) = Seq({ pull = () => Some((value, empty)) })\n"
    + "\n"
    + "(** The sequence that yields `value`, then everything in `rest`. *)\n"
    + "export let prepend(rest: Seq(a), value: a): Seq(a) = Seq({ pull = () => Some((value, rest)) })\n"
    + "\n"
    + "(** The infinite sequence `seed`, `step(seed)`, `step(step(seed))`, and so on.\n"
    + "    Bound it with `take` or `takeWhile` before consuming it. *)\n"
    + "export fun iterate(seed: a, step: a -> a): Seq(a) =\n"
    + "    Seq({ pull = () => Some((seed, iterate(step(seed), step))) })\n"
    + "\n"
    + "(** Applies `transform` to each element as that element is pulled. A traversal\n"
    + "    calls `transform` once per element, so two traversals call it twice —\n"
    + "    `memoize` the result when it is expensive. *)\n"
    + "export fun map(source: Seq(a), transform: a -> b): Seq(b) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) => Some((transform(value), map(rest, transform)))\n"
    + "    })\n"
    + "\n"
    + "(** The first `count` elements of `source`, or all of them if it is shorter. A\n"
    + "    `count` of zero or less gives the empty sequence. *)\n"
    + "export fun take(source: Seq(a), count: Int): Seq(a) =\n"
    + "    if count <= 0 then\n"
    + "        empty\n"
    + "    else\n"
    + "        Seq({ pull = () =>\n"
    + "            match next(source)\n"
    + "                None => None\n"
    + "                Some((value, rest)) => Some((value, take(rest, count - 1)))\n"
    + "        })\n"
    + "\n"
    + "(** The longest leading run of elements satisfying `keep`. The first element\n"
    + "    that fails ends the sequence and is not part of it. *)\n"
    + "export fun takeWhile(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(source)\n"
    + "            None => None\n"
    + "            Some((value, rest)) =>\n"
    + "                if keep(value) then\n"
    + "                    Some((value, takeWhile(rest, keep)))\n"
    + "                else\n"
    + "                    None\n"
    + "    })\n"
    + "\n"
    + "(** Grows a sequence from `seed`: each step produces one element and the seed\n"
    + "    for the next, and `None` ends it. The mirror of `fold`, which consumes one. *)\n"
    + "export fun unfold(seed: b, produce: b -> Option((a, b))): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match produce(seed)\n"
    + "            None => None\n"
    + "            Some((value, nextSeed)) => Some((value, unfold(nextSeed, produce)))\n"
    + "    })\n"
    + "\n"
    + "(** Combines elements pairwise with `combine`, ending as soon as either side\n"
    + "    runs out. *)\n"
    + "export fun zipWith(left: Seq(a), right: Seq(b), combine: (a, b) -> c): Seq(c) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(left)\n"
    + "            None => None\n"
    + "            Some((leftValue, leftRest)) =>\n"
    + "                match next(right)\n"
    + "                    None => None\n"
    + "                    Some((rightValue, rightRest)) =>\n"
    + "                        Some((combine(leftValue, rightValue), zipWith(leftRest, rightRest, combine)))\n"
    + "    })\n"
    + "\n"
    + "(** Pairs elements positionally, ending as soon as either side runs out. *)\n"
    + "export let zip(left: Seq(a), right: Seq(b)): Seq((a, b)) =\n"
    + "    zipWith(left, right, (leftValue, rightValue) => (leftValue, rightValue))\n"
    + "\n"
    + "(** The elements of `first`, then those of `second`. `second` is not pulled\n"
    + "    until `first` is exhausted, so an infinite `first` never reaches it. *)\n"
    + "export fun concat(first: Seq(a), second: Seq(a)): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        match next(first)\n"
    + "            None => next(second)\n"
    + "            Some((value, rest)) => Some((value, concat(rest, second)))\n"
    + "    })\n"
    + "\n"
    + "// Combinators whose step may consume many source elements to yield one.\n"
    + "\n"
    + "(** The elements of `source` satisfying `keep`. One pull consumes source\n"
    + "    elements until it finds one, so pulling past the last match runs the source\n"
    + "    to exhaustion — and does not return at all if the source is infinite. *)\n"
    + "export fun filter(source: Seq(a), keep: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := False\n"
    + "                Some((value, rest)) =>\n"
    + "                    if keep(value) then\n"
    + "                        result := Some((value, filter(rest, keep)))\n"
    + "                        searching := False\n"
    + "                    else\n"
    + "                        current := rest\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** `source` without its first `count` elements. They are skipped on the first\n"
    + "    pull of the result, not when `drop` is called. *)\n"
    + "export let drop(source: Seq(a), count: Int): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var remaining = count\n"
    + "        var result = None\n"
    + "        var running = True\n"
    + "        while running\n"
    + "            if remaining <= 0 then\n"
    + "                result := next(current)\n"
    + "                running := False\n"
    + "            else\n"
    + "                match next(current)\n"
    + "                    None => running := False\n"
    + "                    Some((_, rest)) =>\n"
    + "                        current := rest\n"
    + "                        remaining := remaining - 1\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** `source` from its first element that fails `discard` onward. Like `drop`,\n"
    + "    the skipping happens on the first pull of the result. *)\n"
    + "export let dropWhile(source: Seq(a), discard: a -> Bool): Seq(a) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var current = source\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(current)\n"
    + "                None => searching := False\n"
    + "                Some((value, rest)) =>\n"
    + "                    if discard(value) then\n"
    + "                        current := rest\n"
    + "                    else\n"
    + "                        result := Some((value, rest))\n"
    + "                        searching := False\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "// `flatMap` with the partially consumed inner sequence carried between pulls.\n"
    + "fun flatMapWith(source: Seq(a), transform: a -> Seq(b), pending: Seq(b)): Seq(b) =\n"
    + "    Seq({ pull = () =>\n"
    + "        var outer = source\n"
    + "        var inner = pending\n"
    + "        var result = None\n"
    + "        var searching = True\n"
    + "        while searching\n"
    + "            match next(inner)\n"
    + "                Some((value, rest)) =>\n"
    + "                    result := Some((value, flatMapWith(outer, transform, rest)))\n"
    + "                    searching := False\n"
    + "                None =>\n"
    + "                    match next(outer)\n"
    + "                        None => searching := False\n"
    + "                        Some((outerValue, outerRest)) =>\n"
    + "                            outer := outerRest\n"
    + "                            inner := transform(outerValue)\n"
    + "        result\n"
    + "    })\n"
    + "\n"
    + "(** The sequences `transform` produces, concatenated in order. Each is pulled to\n"
    + "    exhaustion before the next source element is read. *)\n"
    + "export let flatMap(source: Seq(a), transform: a -> Seq(b)): Seq(b) =\n"
    + "    flatMapWith(source, transform, empty)\n"
    + "\n"
    + "// Consumers: drive a `Seq` to a value.\n"
    + "\n"
    + "(** Reduces the whole sequence to one value, left to right, starting from\n"
    + "    `initial`. It pulls every element, so it does not return on an infinite\n"
    + "    sequence. *)\n"
    + "export let fold(source: Seq(a), initial: b, combine: (b, a) -> b): b =\n"
    + "    var accumulator = initial\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((value, rest)) =>\n"
    + "                accumulator := combine(accumulator, value)\n"
    + "                current := rest\n"
    + "    accumulator\n"
    + "\n"
    + "(** How many elements `source` yields. It pulls all of them, so it does not\n"
    + "    return on an infinite sequence. *)\n"
    + "export let length(source: Seq(a)): Int =\n"
    + "    var total = 0\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((_, rest)) =>\n"
    + "                total := total + 1\n"
    + "                current := rest\n"
    + "    total\n"
    + "\n"
    + "(** Runs `action` on each element in order, for its effect. It pulls the whole\n"
    + "    sequence, so it does not return on an infinite one. *)\n"
    + "export let forEach(source: Seq(a), action: a -> Unit): Unit =\n"
    + "    var current = source\n"
    + "    var running = True\n"
    + "    while running\n"
    + "        match next(current)\n"
    + "            None => running := False\n"
    + "            Some((value, rest)) =>\n"
    + "                action(value)\n"
    + "                current := rest\n"
    + "\n"
    + "(** The first element satisfying `matches`, or `None` if none does. It stops at\n"
    + "    that element, so it is safe on an infinite sequence that contains one. *)\n"
    + "export let find(source: Seq(a), matches: a -> Bool): Option(a) =\n"
    + "    var current = source\n"
    + "    var result = None\n"
    + "    var searching = True\n"
    + "    while searching\n"
    + "        match next(current)\n"
    + "            None => searching := False\n"
    + "            Some((value, rest)) =>\n"
    + "                if matches(value) then\n"
    + "                    result := Some(value)\n"
    + "                    searching := False\n"
    + "                else\n"
    + "                    current := rest\n"
    + "    result\n"
    + "\n"
    + "(** Whether any element satisfies `matches`, stopping at the first that does. *)\n"
    + "export let any(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    match find(source, matches)\n"
    + "        None => False\n"
    + "        Some(_) => True\n"
    + "\n"
    + "(** Whether every element satisfies `matches`, stopping at the first that does\n"
    + "    not. *)\n"
    + "export let all(source: Seq(a), matches: a -> Bool): Bool =\n"
    + "    not any(source, value => not matches(value))\n",
  "Result.hex":
    "// The canonical success-or-error union used across the standard library.\n"
    + "export union Result(a, e) =\n"
    + "    | Ok(value: a)\n"
    + "    | Err(error: e)\n",
  "Vector.hex":
    "// The public Vector companion over the compiler's representation core.\n"
    + "\n"
    + "(** Raised when an asserted index addresses no element, from `values[index]`,\n"
    + "    `at`, `set`, or String indexing. `index` is the index as passed and `size`\n"
    + "    the collection's size at the fault. *)\n"
    + "export exception IndexError(index: Int, size: Int)\n"
    + "\n"
    + "(** Raised when a slice is taken with a descending range: a window has no\n"
    + "    direction. `start` and `end` are the range's endpoints as supplied. *)\n"
    + "export exception SliceError(start: Int, end: Int)\n"
    + "\n"
    + "// The whole boundary Collections Part 3 section 7 pins: representation-sensitive\n"
    + "// length and end updates, signed indexed access, persistent indexed update, and\n"
    + "// the eager/lazy bridge. Everything below is ordinary Hexagon over these.\n"
    + "extern from \"hex:intrinsic\"\n"
    + "    (** How many elements `values` holds, in constant time. *)\n"
    + "    export fun vectorLength as length(values: Vector(a)): Int\n"
    + "\n"
    + "    (** `values` with `value` added after its last element. *)\n"
    + "    export fun vectorAppend as append(values: Vector(a), value: a): Vector(a)\n"
    + "\n"
    + "    (** `values` with `value` added before its first element. *)\n"
    + "    export fun vectorPrepend as prepend(values: Vector(a), value: a): Vector(a)\n"
    + "\n"
    + "    (** The element at a signed `index`: 1-based from the start, or from the end\n"
    + "        when negative, so `at(values, -1)` is the last element. Raises\n"
    + "        `IndexError` when no such element exists — zero never addresses one. *)\n"
    + "    export fun vectorAt as at(values: Vector(a), index: Int): a\n"
    + "\n"
    + "    (** `values` with the element at 1-based `index` replaced by `value`. Raises\n"
    + "        `IndexError` when `index` is out of range; it never extends the vector. *)\n"
    + "    export fun vectorSet as set(values: Vector(a), index: Int, value: a): Vector(a)\n"
    + "\n"
    + "    (** The elements of `values` as a sequence, in order. *)\n"
    + "    export fun vectorToSeq as toSeq(values: Vector(a)): Seq(a)\n"
    + "\n"
    + "    (** The elements of `values` collected into a vector. It forces the whole\n"
    + "        sequence, so it does not terminate on an infinite one. *)\n"
    + "    export fun vectorFromSeq as fromSeq(values: Seq(a)): Vector(a)\n"
    + "\n"
    + "(** The empty vector. *)\n"
    + "export let empty: Vector(a) = []\n"
    + "\n"
    + "(** A vector with a single value. *)\n"
    + "export let singleton(value: a): Vector(a) = [value]\n"
    + "\n"
    + "(** Whether `values` holds no elements. *)\n"
    + "export let isEmpty(values: Vector(a)): Bool = length(values) == 0\n"
    + "\n"
    + "(** The first element of `values`, or `None` when it is empty. *)\n"
    + "export let first(values: Vector(a)): Option(a) = match values\n"
    + "    [] => None\n"
    + "    [value, ...] => Some(value)\n"
    + "\n"
    + "(** The last element of `values`, or `None` when it is empty. *)\n"
    + "export let last(values: Vector(a)): Option(a) = match values\n"
    + "    [] => None\n"
    + "    [..., value] => Some(value)\n"
    + "\n"
    + "(** `values` without its first element. The empty vector stays empty. *)\n"
    + "export let dropFirst(values: Vector(a)): Vector(a) = match values\n"
    + "    [] => []\n"
    + "    [_, ...rest] => rest\n"
    + "\n"
    + "(** `values` without its last element. The empty vector stays empty. *)\n"
    + "export let dropLast(values: Vector(a)): Vector(a) = match values\n"
    + "    [] => []\n"
    + "    [...rest, _] => rest\n"
    + "\n"
    + "(** The element at 1-based `index`, or `None` when there is none. The total\n"
    + "    accessor: out of bounds is an answer, not a fault. *)\n"
    + "export let get(values: Vector(a), index: Int): Option(a) =\n"
    + "    if index < 1 or index > length(values) then\n"
    + "        None\n"
    + "    else\n"
    + "        Some(values[index])\n",
};
