/**
 * Embedded copies of the canonical `runtime/` runtime sources. Do not edit by hand.
 * Regenerate with `npm run generate:prelude`; a conformance test asserts these
 * never drift from the originals.
 */

export const RUNTIME_SOURCES: Readonly<Record<string, string>> = {
  "VectorTrie.hex":
    "// The persistent 32-way bit-partitioned trie backing `Vector(a)` (Collections\n"
    + "// Part 3 §4), written over the hidden fixed-32 `Node` intrinsic. This is a\n"
    + "// runtime-internal module: it is compiled only as a privileged runtime module,\n"
    + "// and `Tree`, `Node`, and `TrieVector` never cross a module boundary — the\n"
    + "// public face is `Vector(a)`, and the emitter is what wires the two together.\n"
    + "// Index math uses `Int.div`/`Int.mod` by the branch factor; Hexagon has no\n"
    + "// bitwise operators, and none are needed.\n"
    + "//\n"
    + "// Nothing here is `export`ed, and it could not be: every operation's type names\n"
    + "// `TrieVector`, and exporting one is refused as exposing a private type. The\n"
    + "// emitted JavaScript is what carries the operations out, under an export list\n"
    + "// the emitter writes — so no Hexagon module can import this one, by name or by\n"
    + "// accident, however the compiler happens to place the file.\n"
    + "//\n"
    + "// **This module must not reference anything the prelude's `Vector` machinery\n"
    + "// reaches.** It sees the whole prelude, and a vector literal, bracket, pattern,\n"
    + "// or `Vector.` call written here would make the emitted `VectorTrie.js` import\n"
    + "// `Vector.js`, which already imports this one — a module cycle nothing in the\n"
    + "// compiler would report, because it is created at emission and not by any\n"
    + "// `import` item. `vector-trie-wiring.test.ts` pins the emitted module's import\n"
    + "// list empty, which is that rule made checkable.\n"
    + "\n"
    + "// A trie node is either a leaf holding up to 32 values, or a branch holding up\n"
    + "// to 32 child subtrees. Both are 32-slot `Node`s; which slots are populated is\n"
    + "// tracked by the enclosing `TrieVector`'s count, never by reading empty slots.\n"
    + "union Tree(a) =\n"
    + "    | Leaf(values: Node(a))\n"
    + "    | Branch(children: Node(Tree(a)))\n"
    + "\n"
    + "// The Vector representation, following Immutable.js's List. Elements live in a\n"
    + "// virtual internal index space; `origin` is the internal index of logical\n"
    + "// element 0 and `capacity` the internal index just past the last, so the logical\n"
    + "// size is `capacity - origin`. `root` addresses the internal range `[0, radix^height)`;\n"
    + "// the `tail` buffer holds the internal range `[tailOffset(capacity), capacity)`\n"
    + "// (its final up-to-32 elements), and the tree holds `[0, tailOffset(capacity))`.\n"
    + "// `height` counts `root`'s levels: 1 => a `Leaf`, 2 => a `Branch` of leaves.\n"
    + "//\n"
    + "// The two ends are NOT symmetric. `append` is favoured: it lands elements in the\n"
    + "// tail at the high end, packed left-to-right, exactly as a plain append-only trie\n"
    + "// would. `prepend` walks `origin` downward through the headroom below the live\n"
    + "// range and, when it runs out, grows a fresh level at the *left* (the old root\n"
    + "// dropped into a non-zero child slot), rebasing `origin`/`capacity` by that\n"
    + "// level's span — so a non-zero `origin` can leave the tree's left edge only\n"
    + "// partially populated. Every lookup addresses by `index + origin`, which is what\n"
    + "// lets both ends stay amortized O(1) over one shared trie.\n"
    + "record TrieVector(a) = {\n"
    + "    origin: Int,\n"
    + "    capacity: Int,\n"
    + "    height: Int,\n"
    + "    root: Tree(a),\n"
    + "    tail: Node(a),\n"
    + "}\n"
    + "\n"
    + "// Signals a structurally malformed trie (a runtime bug, never a caller error).\n"
    + "// Thrown only on paths a well-formed trie can never take.\n"
    + "exception TrieCorruption(message: String)\n"
    + "\n"
    + "// The branch factor. A `Node` is always exactly this wide.\n"
    + "let radix: Int = 32\n"
    + "\n"
    + "// The one empty vector. A `TrieVector` is immutable, so every empty vector in a\n"
    + "// program can be this same value rather than a fresh five-field record over two\n"
    + "// fresh 32-slot `Node`s.\n"
    + "let empty: TrieVector(a) =\n"
    + "    TrieVector({\n"
    + "        origin = 0,\n"
    + "        capacity = 0,\n"
    + "        height = 1,\n"
    + "        root = Leaf(Node.empty()),\n"
    + "        tail = Node.empty(),\n"
    + "    })\n"
    + "\n"
    + "fun size<a>(trie: TrieVector(a)): Int = trie.capacity - trie.origin\n"
    + "\n"
    + "fun isEmpty<a>(trie: TrieVector(a)): Bool = trie.capacity == trie.origin\n"
    + "\n"
    + "// The internal index at which the `tail` begins: the largest multiple of `radix`\n"
    + "// not exceeding the last populated internal index. The tree holds `[0, tailOffset)`\n"
    + "// and the tail holds `[tailOffset, capacity)`, so `capacity - tailOffset` (the\n"
    + "// tail length) is always 1..32, or 0 only when the whole vector is empty.\n"
    + "fun tailOffset(capacity: Int): Int =\n"
    + "    if capacity == 0 then\n"
    + "        0\n"
    + "    else\n"
    + "        Int.div(capacity - 1, radix) * radix\n"
    + "\n"
    + "// `radix` raised to `exponent` (exponent >= 0), computed without a power\n"
    + "// operator. `leafCapacity(height) = pow32(height - 1)` is the number of leaves a\n"
    + "// height-`h` trie holds when full.\n"
    + "fun pow32(exponent: Int): Int =\n"
    + "    var result = 1\n"
    + "    for step in 1..exponent\n"
    + "        result := result * radix\n"
    + "    result\n"
    + "\n"
    + "// Reads the element at an absolute `internal` index. Indices at or beyond\n"
    + "// `tailOffset` live in the tail; the rest descend `root` one branch level per\n"
    + "// iteration to the owning leaf, then select the low digit within it. Callers\n"
    + "// guarantee the index is populated, so no empty `Node` slot is ever read.\n"
    + "fun readInternal<a>(trie: TrieVector(a), internal: Int): a =\n"
    + "    if internal >= tailOffset(trie.capacity) then\n"
    + "        Node.get(trie.tail, internal - tailOffset(trie.capacity))\n"
    + "    else\n"
    + "        var node: Tree(a) = trie.root\n"
    + "        var span = pow32(trie.height - 1)\n"
    + "        var remaining = internal\n"
    + "        // A height-`h` trie has `h - 1` branch levels above its leaves.\n"
    + "        for level in 2..trie.height\n"
    + "            node := match node\n"
    + "                Branch(children) => Node.get(children, Int.div(remaining, span))\n"
    + "                Leaf(_) => node\n"
    + "            remaining := Int.mod(remaining, span)\n"
    + "            span := Int.div(span, radix)\n"
    + "        match node\n"
    + "            Leaf(values) => Node.get(values, remaining)\n"
    + "            // Unreachable for a populated path (the loop always lands on a leaf).\n"
    + "            Branch(_) => throw(TrieCorruption(\"readInternal: descent did not reach a leaf\"))\n"
    + "\n"
    + "// Reads the element at 0-based logical `index`; the internal index is\n"
    + "// `index + origin`. Callers guarantee `0 <= index < size`.\n"
    + "fun get<a>(trie: TrieVector(a), index: Int): a =\n"
    + "    readInternal(trie, index + trie.origin)\n"
    + "\n"
    + "// Locates 0-based logical `index` for *sequential* reading: the 32-slot `Node`\n"
    + "// that holds it, the offset of `index` within that node, and the run — how many\n"
    + "// consecutive elements starting at `index` that same node holds. A traversal\n"
    + "// that asks again at `index + run` visits each node once and descends once per\n"
    + "// node, so a whole vector costs O(n) rather than the O(n log32 n) an\n"
    + "// element-at-a-time `get` walk would. Callers guarantee `0 <= index < size`, and\n"
    + "// the returned run is always at least 1.\n"
    + "//\n"
    + "// The descent is `readInternal`'s; only the last step differs, returning the\n"
    + "// leaf's whole `Node` instead of one slot. The run is capped twice: by what is\n"
    + "// left of the node (`radix - remaining`), and by the region boundary — the tail\n"
    + "// ends at `capacity`, a tree leaf ends where the tail begins.\n"
    + "fun nodeRun<a>(trie: TrieVector(a), index: Int): (Node(a), Int, Int) =\n"
    + "    let internal = index + trie.origin\n"
    + "    let off = tailOffset(trie.capacity)\n"
    + "    if internal >= off then\n"
    + "        (trie.tail, internal - off, trie.capacity - internal)\n"
    + "    else\n"
    + "        var node: Tree(a) = trie.root\n"
    + "        var span = pow32(trie.height - 1)\n"
    + "        var remaining = internal\n"
    + "        for level in 2..trie.height\n"
    + "            node := match node\n"
    + "                Branch(children) => Node.get(children, Int.div(remaining, span))\n"
    + "                Leaf(_) => node\n"
    + "            remaining := Int.mod(remaining, span)\n"
    + "            span := Int.div(span, radix)\n"
    + "        let inNode = radix - remaining\n"
    + "        let inRegion = off - internal\n"
    + "        let run = if inNode < inRegion then inNode else inRegion\n"
    + "        match node\n"
    + "            Leaf(values) => (values, remaining, run)\n"
    + "            // Unreachable for a populated path (the loop always lands on a leaf).\n"
    + "            Branch(_) => throw(TrieCorruption(\"nodeRun: descent did not reach a leaf\"))\n"
    + "\n"
    + "// Wraps `leaf` in `levels` fresh branch nodes, forming the left spine of a new\n"
    + "// subtree. `newPath(0, leaf) = leaf`.\n"
    + "fun newPath<a>(levels: Int, leaf: Tree(a)): Tree(a) =\n"
    + "    var node: Tree(a) = leaf\n"
    + "    for step in 1..levels\n"
    + "        node := Branch(Node.set(Node.empty(), 0, node))\n"
    + "    node\n"
    + "\n"
    + "// Inserts `leaf` at 0-based leaf position `p` into a copy of `node` (a height-`h`\n"
    + "// subtree with room for it). Left-packed: `p`'s digit at this level is a new\n"
    + "// child exactly when the position within that child is 0. Recursion depth is\n"
    + "// bounded by `h` (<= ~7 for billions of elements), so this is stack-safe.\n"
    + "fun insertLeaf<a>(node: Tree(a), height: Int, p: Int, leaf: Tree(a)): Tree(a) =\n"
    + "    match node\n"
    + "        // Only reached at height 1: the empty root leaf is replaced by the first\n"
    + "        // flushed leaf.\n"
    + "        Leaf(_) => leaf\n"
    + "        Branch(children) =>\n"
    + "            let childLeaves = pow32(height - 2)\n"
    + "            let childIndex = Int.div(p, childLeaves)\n"
    + "            let childPos = Int.mod(p, childLeaves)\n"
    + "            if childPos == 0 then\n"
    + "                Branch(Node.set(children, childIndex, newPath(height - 2, leaf)))\n"
    + "            else\n"
    + "                let child = Node.get(children, childIndex)\n"
    + "                Branch(Node.set(children, childIndex, insertLeaf(child, height - 1, childPos, leaf)))\n"
    + "\n"
    + "// Flushes a full tail (as `Leaf(tail)`) into `root`, returning the new root and\n"
    + "// its height. `treeExtent` is the internal extent already held by `root` (a\n"
    + "// multiple of 32 — the internal index where the flushed leaf lands). When `root`\n"
    + "// is full at its height, the trie grows one level at the right (append's end).\n"
    + "fun flushLeaf<a>(root: Tree(a), height: Int, treeExtent: Int, leaf: Tree(a)): (Tree(a), Int) =\n"
    + "    let leafPos = Int.div(treeExtent, radix)\n"
    + "    let capacity = pow32(height - 1)\n"
    + "    if leafPos == capacity then\n"
    + "        // Root is full: a new level whose slot 0 is the old root and slot 1 is a\n"
    + "        // fresh spine down to the new leaf.\n"
    + "        let grown = Branch(Node.set(Node.set(Node.empty(), 0, root), 1, newPath(height - 1, leaf)))\n"
    + "        (grown, height + 1)\n"
    + "    else\n"
    + "        (insertLeaf(root, height, leafPos, leaf), height)\n"
    + "\n"
    + "fun append<a>(trie: TrieVector(a), value: a): TrieVector(a) =\n"
    + "    let cap = trie.capacity\n"
    + "    let off = tailOffset(cap)\n"
    + "    let tailLen = cap - off\n"
    + "    if tailLen < radix then\n"
    + "        TrieVector({\n"
    + "            origin = trie.origin,\n"
    + "            capacity = cap + 1,\n"
    + "            height = trie.height,\n"
    + "            root = trie.root,\n"
    + "            tail = Node.set(trie.tail, tailLen, value),\n"
    + "        })\n"
    + "    else\n"
    + "        // Tail is full: flush it as one leaf at internal index `off`, then start a\n"
    + "        // fresh tail holding the new value.\n"
    + "        let (newRoot, newHeight) = flushLeaf(trie.root, trie.height, off, Leaf(trie.tail))\n"
    + "        TrieVector({\n"
    + "            origin = trie.origin,\n"
    + "            capacity = cap + 1,\n"
    + "            height = newHeight,\n"
    + "            root = newRoot,\n"
    + "            tail = Node.set(Node.empty(), 0, value),\n"
    + "        })\n"
    + "\n"
    + "// A fresh, empty subtree of the given height, ready to be filled: a `Leaf` at\n"
    + "// height 1, a `Branch` at any greater height.\n"
    + "fun freshSubtree<a>(height: Int): Tree(a) =\n"
    + "    if height == 1 then\n"
    + "        Leaf(Node.empty())\n"
    + "    else\n"
    + "        Branch(Node.empty())\n"
    + "\n"
    + "// Writes `value` at internal `index` into a copy of `node` (a height-`h`\n"
    + "// subtree), creating any missing nodes along the path. Prepend fills the headroom\n"
    + "// below `origin` strictly downward, so the *first* write into a child always\n"
    + "// lands at that child's top slot (`childPos == span - 1`) — the signal that the\n"
    + "// child is fresh; every lower position reuses the child a previous prepend made.\n"
    + "// Recursion depth is bounded by `h`, so this is stack-safe.\n"
    + "fun writeValue<a>(node: Tree(a), height: Int, index: Int, value: a): Tree(a) =\n"
    + "    match node\n"
    + "        // Height 1: `index` selects the slot within the leaf directly.\n"
    + "        Leaf(values) => Leaf(Node.set(values, index, value))\n"
    + "        Branch(children) =>\n"
    + "            let span = pow32(height - 1)\n"
    + "            let childIndex = Int.div(index, span)\n"
    + "            let childPos = Int.mod(index, span)\n"
    + "            if childPos == span - 1 then\n"
    + "                // First write into this child: it is fresh.\n"
    + "                Branch(Node.set(children, childIndex, writeValue(freshSubtree(height - 1), height - 1, childPos, value)))\n"
    + "            else\n"
    + "                let child = Node.get(children, childIndex)\n"
    + "                Branch(Node.set(children, childIndex, writeValue(child, height - 1, childPos, value)))\n"
    + "\n"
    + "fun prepend<a>(trie: TrieVector(a), value: a): TrieVector(a) =\n"
    + "    if trie.capacity == trie.origin then\n"
    + "        // Empty: the sole element is both front and back, so it lands in the tail\n"
    + "        // (the favoured end) as a singleton — growing a tree here would leave\n"
    + "        // `tailOffset(capacity)` at 0 and mask the write.\n"
    + "        TrieVector({\n"
    + "            origin = 0,\n"
    + "            capacity = 1,\n"
    + "            height = 1,\n"
    + "            root = Leaf(Node.empty()),\n"
    + "            tail = Node.set(Node.empty(), 0, value),\n"
    + "        })\n"
    + "    else if trie.origin > 0 then\n"
    + "        // Headroom remains below the live range: write at internal `origin - 1`.\n"
    + "        // If the entire live range is tail-resident (a small window), that index\n"
    + "        // falls in the tail; otherwise it descends the tree.\n"
    + "        let newOrigin = trie.origin - 1\n"
    + "        let off = tailOffset(trie.capacity)\n"
    + "        if newOrigin >= off then\n"
    + "            TrieVector({\n"
    + "                origin = newOrigin,\n"
    + "                capacity = trie.capacity,\n"
    + "                height = trie.height,\n"
    + "                root = trie.root,\n"
    + "                tail = Node.set(trie.tail, newOrigin - off, value),\n"
    + "            })\n"
    + "        else\n"
    + "            TrieVector({\n"
    + "                origin = newOrigin,\n"
    + "                capacity = trie.capacity,\n"
    + "                height = trie.height,\n"
    + "                root = writeValue(trie.root, trie.height, newOrigin, value),\n"
    + "                tail = trie.tail,\n"
    + "            })\n"
    + "    else\n"
    + "        // No headroom (origin == 0, non-empty): grow a level at the left. The old\n"
    + "        // root drops into slot 1 of a fresh branch, leaving slot 0's whole span\n"
    + "        // (`radix^height`) as new headroom; `origin`/`capacity` rebase by that span\n"
    + "        // (a multiple of `radix`, so the tail's slots are unmoved). The new front\n"
    + "        // is `span - 1`, which is below the shifted `tailOffset`, so it descends\n"
    + "        // the tree. (For a tail-only vector the old empty root sits unread in slot\n"
    + "        // 1 and the tree fills slot 0.)\n"
    + "        let span = pow32(trie.height)\n"
    + "        let grown: Tree(a) = Branch(Node.set(Node.empty(), 1, trie.root))\n"
    + "        let newHeight = trie.height + 1\n"
    + "        let newOrigin = span - 1\n"
    + "        TrieVector({\n"
    + "            origin = newOrigin,\n"
    + "            capacity = trie.capacity + span,\n"
    + "            height = newHeight,\n"
    + "            root = writeValue(grown, newHeight, newOrigin, value),\n"
    + "            tail = trie.tail,\n"
    + "        })\n"
    + "\n"
    + "// Replaces the element at internal `index` (a populated position) in a copy of\n"
    + "// `node`, descending to its leaf. Unlike `writeValue` every node on the path\n"
    + "// already exists, so no slot is created — a persistent overwrite.\n"
    + "fun updateAt<a>(node: Tree(a), height: Int, index: Int, value: a): Tree(a) =\n"
    + "    match node\n"
    + "        Leaf(values) => Leaf(Node.set(values, index, value))\n"
    + "        Branch(children) =>\n"
    + "            let span = pow32(height - 1)\n"
    + "            let childIndex = Int.div(index, span)\n"
    + "            let childPos = Int.mod(index, span)\n"
    + "            Branch(Node.set(children, childIndex, updateAt(Node.get(children, childIndex), height - 1, childPos, value)))\n"
    + "\n"
    + "// Persistent update at 0-based logical `index` (caller guarantees it is in range;\n"
    + "// the public `Vector.set` owns the `IndexError` bounds assertion). A tail slot is\n"
    + "// rewritten directly; a tree position descends via `updateAt`.\n"
    + "fun set<a>(trie: TrieVector(a), index: Int, value: a): TrieVector(a) =\n"
    + "    let internal = index + trie.origin\n"
    + "    let off = tailOffset(trie.capacity)\n"
    + "    if internal >= off then\n"
    + "        TrieVector({\n"
    + "            origin = trie.origin,\n"
    + "            capacity = trie.capacity,\n"
    + "            height = trie.height,\n"
    + "            root = trie.root,\n"
    + "            tail = Node.set(trie.tail, internal - off, value),\n"
    + "        })\n"
    + "    else\n"
    + "        TrieVector({\n"
    + "            origin = trie.origin,\n"
    + "            capacity = trie.capacity,\n"
    + "            height = trie.height,\n"
    + "            root = updateAt(trie.root, trie.height, internal, value),\n"
    + "            tail = trie.tail,\n"
    + "        })\n"
    + "\n"
    + "// Returns the sub-vector over 0-based half-open logical window `[begin, end)`\n"
    + "// (caller guarantees `0 <= begin <= end <= size`; the public `Vector` bracket\n"
    + "// owns clamping and the descending-range `SliceError`). The window becomes a new\n"
    + "// `origin`/`capacity` over the *same* trie, so any window whose tail region is a\n"
    + "// prefix of the current one — end slices, `dropFirst`/`dropLast` — is O(1). When\n"
    + "// the new capacity lands the tail elsewhere, only the tail (<= 32 elements) is\n"
    + "// rebuilt from their current positions; the tree is shared untouched.\n"
    + "fun slice<a>(trie: TrieVector(a), begin: Int, end: Int): TrieVector(a) =\n"
    + "    if begin >= end then\n"
    + "        empty\n"
    + "    else\n"
    + "        let newOrigin = trie.origin + begin\n"
    + "        let newCapacity = trie.origin + end\n"
    + "        let newOff = tailOffset(newCapacity)\n"
    + "        if newOff == tailOffset(trie.capacity) and newCapacity <= trie.capacity then\n"
    + "            // The new tail is a prefix of the current one: reuse both fields as-is\n"
    + "            // (any tail slots past the new capacity are simply never addressed).\n"
    + "            TrieVector({\n"
    + "                origin = newOrigin,\n"
    + "                capacity = newCapacity,\n"
    + "                height = trie.height,\n"
    + "                root = trie.root,\n"
    + "                tail = trie.tail,\n"
    + "            })\n"
    + "        else\n"
    + "            // Rebuild the tail from internal `[liveStart, newCapacity)`. When the\n"
    + "            // window is shorter than a full tail, `newOff` sits below `newOrigin`;\n"
    + "            // the tail slots beneath the origin stay empty and are never read.\n"
    + "            let liveStart = if newOrigin > newOff then newOrigin else newOff\n"
    + "            var newTail: Node(a) = Node.empty()\n"
    + "            for internal in liveStart..(newCapacity - 1)\n"
    + "                newTail := Node.set(newTail, internal - newOff, readInternal(trie, internal))\n"
    + "            TrieVector({\n"
    + "                origin = newOrigin,\n"
    + "                capacity = newCapacity,\n"
    + "                height = trie.height,\n"
    + "                root = trie.root,\n"
    + "                tail = newTail,\n"
    + "            })\n"
    + "\n"
    + "// `slice` with the bounds intersected against `[0, size)` first, which is the\n"
    + "// clamping the public bracket promises (Collections Part 3 §6.1): a window that\n"
    + "// runs off either end keeps only the part that exists, and one wholly outside is\n"
    + "// the empty vector. Direction is not this function's business — a descending\n"
    + "// `Range` never reaches here, it faults at the bracket (§6.3).\n"
    + "fun window<a>(trie: TrieVector(a), begin: Int, end: Int): TrieVector(a) =\n"
    + "    let count = size(trie)\n"
    + "    let low = if begin < 0 then 0 else begin\n"
    + "    let high = if end > count then count else end\n"
    + "    if low >= high then\n"
    + "        empty\n"
    + "    else\n"
    + "        slice(trie, low, high)\n"
    + "\n"
    + "// `++` at `Vector(a)` (Operators §7): the elements of `right` appended to `left`\n"
    + "// in order. Linear in `right` as Part 1 §2.2 documents, times `append`'s\n"
    + "// amortized-constant cost. `left` is not copied — the result grows out of it,\n"
    + "// sharing its whole trie — so `xs ++ []` is `xs` itself.\n"
    + "//\n"
    + "// `right` is read in leaf runs, not element by element: `nodeRun` descends once\n"
    + "// per 32-slot `Node` and reports how far that node reaches, and the inner loop\n"
    + "// then reads the run out of it with no further descent. A `get` per element\n"
    + "// would be a fresh O(log32 m) descent each time — correct, and quietly\n"
    + "// O(m log32 m) against Part 1 §2.2's linear `++`. The descent count for a whole\n"
    + "// concat is therefore ceil(m / 32) (one more wherever a region boundary splits a\n"
    + "// node), which `vector-trie-wiring.test.ts` pins by counting the descents a\n"
    + "// whole concat makes.\n"
    + "fun concat<a>(left: TrieVector(a), right: TrieVector(a)): TrieVector(a) =\n"
    + "    let count = size(right)\n"
    + "    var result: TrieVector(a) = left\n"
    + "    var index = 0\n"
    + "    while index < count\n"
    + "        let (values, offset, run) = nodeRun(right, index)\n"
    + "        // `run` is at least 1, so this range is never empty.\n"
    + "        for step in 0..(run - 1)\n"
    + "            result := append(result, Node.get(values, offset + step))\n"
    + "        index := index + run\n"
    + "    result\n",
};
